//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuestEditor.rc
//
#define IDS_CELL_TYPES_ADDED_SUCCESSFULL 1
#define IDS_MINIGAMES_NODE              2
#define IDS_ERR_CONVERT_TO_XML_FAILED   3
#define IDOK2                           3
#define IDS_FILE_CONVERTER_XML_FILE_EXIST_OVERWRITE 4
#define IDS_FILE_CONVERTER_FILE_EXIST_SELECT_NEW 5
#define IDS_NODE_NAME_ZONE_ON           6
#define IDS_NODE_NAME_ZONE_OFF          7
#define IDS_NODE_NAME_ZONE_TOGGLE       8
#define IDS_NODE_NAME_ZONE_ON_SHORT     9
#define IDS_NODE_NAME_ZONE_OFF_SHORT    10
#define IDS_NODE_NAME_ZONE_TOGGLE_SHORT 11
#define IDS_DEL_INVENTORY_USED_REMOVE   12
#define IDS_CANNT_REMOVE_LAST_CELL_TYPE 13
#define IDS_MINI_GAME_EXE_FILE_NAME     13
#define IDS_DEL_CELL_TYPE_MSG           14
#define IDS_MULTIWIZARD_IDCANCEL_CAP    15
#define IDS_NEW_PRJ_WIZ_CAP             16
#define IDS_MUSIC_TRACKS_NODE           17
#define IDS_NEW_MUSIC_TRACK_NAME        18
#define IDS_OPEN_MUSIC_TRACK_TITLE      19
#define IDS_MUSIC_TRACK_STOP            20
#define IDS_MUSIC_TRACK_PLAY            21
#define IDS_REMOVE_LAST_CELL_TYPE       22
#define IDS_CNT_LOAD_MINI_GAME_EXE      23
#define IDS_MATERIALS_CATALOG           24
#define IDS_SCENE_NAME_TMPL             25
#define IDS_MAKE_DIR_STRUCT_WIZARD_STRUCT 26
#define IDS_OSD_CAP_QDA_TGA_SELECT      27
#define IDS_CANNT_CRT_DEFAULT_RESOUCES  28
#define IDS_ERR_NO_ANIMATION_FOUND      29
#define IDS_INI_SEC_NAME_ANIM_ASSEMBLING 30
#define IDS_INI_KEY_NAME_CADR_DUR       31
#define IDS_COND_TMPL_OBJ_IN_STATE      32
#define IDS_REMOVE_EDGES_QUESTION       33
#define IDS_TXT_FILES_LIST_EMPTY        34
#define IDS_SOUND_LIST_EMPTY            35
#define IDS_INTERFACE_NODE              36
#define IDS_COND_TMPL_MOUSE_ZONE_CLICK  37
#define IDS_COND_TMPL_OBJ_WAS_IN_STATE  38
#define IDS_COND_TMPL_OBJ_WAS_NEWER_IN_STATE 39
#define IDS_COND_TMPL_MOUSE_OBJECT_ZONE_CLICK 40
#define IDS_COND_DLG_OBJ_ZONE_CLICK_STATIC_CAP 41
#define IDS_CAM_MODE_OBJECT_ON_SCREEN   42
#define IDS_CAM_MODE_CENTER_OBJECT      43
#define IDS_CAM_MODE_FOLLOW_OBJECT      44
#define IDS_CAM_MODE_CENTER_OBJECT_WHEN_LEAVING 45
#define IDS_CAM_MODE_UNASSIGNED         46
#define IDS_PROPPAGE_CAPTION_ADD_STATES_MOUSE_OBJ 47
#define IDS_DEFAULT_CURSOR_NAME         48
#define IDS_FILE_MUST_EXIST             49
#define IDS_PPCAP_VIDEO_PROPERTIES      50
#define IDS_STRING51                    51
#define IDS_COND_TMPL_OBJ_NOT_IN_STATE  51
#define IDS_NO_CURSOR                   52
#define IDS_PPCAP_INVENTORY_PROPERTIES  53
#define IDS_COND_TMPL_OBJ_IN_STATE_NOT  54
#define IDS_COND_TMPL_MOUSE_ZONE_CLICK_NOT 55
#define IDS_COND_TMPL_MOUSE_OBJECT_ZONE_CLICK_NOT 56
#define IDS_COND_TMPL_OBJ_WAS_IN_STATE_NOT 57
#define IDS_COND_TMPL_OBJS_DISTANCE_NOT 58
#define IDS_COND_TMPL_OBJS_DISTANCE     59
#define IDS_COND_TMPL_PERS_ACTIVE       60
#define IDS_COND_TMPL_PERS_ACTIVE_NOT   61
#define IDS_NEW_INTEF_SCREEN_NAME       62
#define IDS_NEW_INTEF_BACK_NAME         63
#define IDS_NEW_INTEF_BTN_NAME          64
#define IDS_NEW_INTEF_SLIDER_NAME       65
#define IDS_INTERF_BTN_PROPERTIES       66
#define IDS_INTERF_SLIDER_PROPERTIES    67
#define IDS_INTERF_BACK_PROPERTIES      68
#define IDS_INTERF_SCREEN_PROPERTIES    69
#define IDS_OPEN_INTERF_SOUND_FILTER    70
#define IDS_OSD_CAP_INTERF_SOUND_SELECT 71
#define IDS_INTRF_ELE_STATE_MODE_DEFAULT 72
#define IDS_INTRF_ELE_STATE_MODE_MOUSE_OVER 73
#define IDS_INTRF_ELE_STATE_MODE_EVENT  74
#define IDS_STRING75                    75
#define IDS_STRING76                    76
#define IDS_STRING77                    77
#define IDS_WIZARD_CAP_ADD_INTERF_BACK  78
#define IDS_WIZARD_CAP_ADD_INTERF_SLIDER 79
#define IDS_WIZARD_CAP_ADD_INTERF_BUTTON 80
#define IDS_PAGE_CAP_IMAGE              81
#define IDS_PAGE_CAP_SLDR_FOREGR_ANIM_AND_SOUND 82
#define IDS_PAGE_CAP_SLDR_BACK_ANIM     83
#define IDS_PAGE_CAP_SELECT_STATE_NAME  84
#define IDS_PAGE_CAP_BTN_ANIM_SOUND     85
#define IDS_PAGE_CAP_DEF_SEL_NAME       86
#define IDS_DLG_CAP_EDIT_STATE          87
#define IDS_ERR_SAVE_FAILED             88
#define IDS_AND_GROUP_NAME              89
#define IDS_OR_GROUP_NAME               90
#define IDS_SELECT_ONE                  91
#define IDS_DISK_VIDEO_CATALOG          92
#define IDS_DISK_MUSIC_CATALOG          93
#define IDS_DISK_INTERFACE_CATALOG      94
#define IDS_DISK_INVENTORY_CATALOG      95
#define IDS_DISK_WAVS_CATALOG           96
#define IDS_DISK_DIALOGS_CATALOG        97
#define IDS_DISK_CHARACTERS_CATALOG     98
#define IDS_DLG_CAP_STATE_COND          99
#define IDD_ABOUTBOX                    100
#define IDS_DLG_CAP_CO_COND             100
#define IDD_DIALOG_MOVING               101
#define IDC_COND_OBJ_CONDITION          101
#define IDS_ASK_FOR_OFFSET_ALL_STATES   101
#define IDS_EVENT_EXIT                  102
#define IDS_EVENT_LOAD_GAME             103
#define IDS_EVENT_SAVE_GAME             104
#define IDC_POINTER                     104
#define IDS_EVENT_NEW_GAME              105
#define IDC_POINTER_COPY                105
#define IDD_PROPPAGE_SCENE_MAIN_PLANE   106
#define IDS_EVENT_CHANGE_INTERFACE_SCREEN 106
#define IDC_NODROP                      106
#define IDD_PROPPAGE_OBJECT_STAT        107
#define IDS_EVENT_CHANGE_PERSONAGE      107
#define IDD_ANIMATION_LIST              108
#define IDS_EVENT_TMP_HIDE_ELEMENT      108
#define IDS_EVENT_HIDE_ELEMENT          109
#define IDD_PROPPAGE_OBJECT_ANIM_STATES 110
#define IDS_EVENT_SHOW_ELEMENT          110
#define IDS_EVENT_RESUME_GAME           111
#define IDD_PROPPAGE_SCENE_GENERAL      112
#define IDS_EVENT_SET_SAVE_MODE         112
#define IDS_EVENT_SET_LOAD_MODE         113
#define IDS_EVENT_ACTIVATE_PERSONAGE    114
#define CG_IDD_PROGRESS                 115
#define IDS_EVENT_PREV_ELEMENT_STATE    115
#define CG_IDS_PROGRESS_CAPTION         116
#define IDS_PROPSHT_CAPTION             117
#define IDD_PROPPAGE_GAME_SETTINGS      118
#define IDS_EVENT_NEXT_ELEMENT_STATE    118
#define IDS_AFTER_ANIMATION             119
#define IDD_PO_PROPPAGE_GEN_SETTINGS    120
#define IDS_BEFORE_ANIMATION            120
#define IDC_MUSIC_TRACK_PLAY            121
#define IDS_CLMN_ACTION                 121
#define IDC_PLAY_MINIGAME               122
#define IDS_CLMN_EXECUTE                122
#define IDC_MAKE_DIR_STRUCT             123
#define IDS_CLMN_PARAMETER              123
#define IDS_WIZARD_CAP_ADD_INTERF_BUTTON_STATE 124
#define IDS_WIZARD_CAP_ADD_INTERF_SAVE  125
#define IDS_INTERF_SAVE_PROPERTIES      126
#define IDS_FILE_MUST_EXIST2            127
#define IDS_FILE_MUST_EXIST_OR_NO_NAME  127
#define IDR_MAINFRAME                   128
#define IDS_CAP_SLIDER_BACKGRND_PROP    129
#define IDS_CAP_SLIDER_FORGRND_PROP     130
#define IDD_PROPPAGE_OBJECT_POS         131
#define IDS_COND_TMPL_OBJ_STATE_WAITING 131
#define IDR_SCENE_NODE                  132
#define IDD_PROPPAGE_AA_PROGRES         132
#define IDS_COND_TMPL_OBJ_STATE_WAITING_NOT 132
#define IDR_GLOBAL_NODE                 133
#define IDC_CREATE_MINIGAME             133
#define IDC_CRT_ANIM_OBJS               134
#define IDR_SCENES_NODE                 135
#define IDS_CNT_LOAD_LAST_NAIL_EXE      135
#define IDR_ANIMATIONS_NODE             136
#define IDS_LAST_NAIL_PROJ_NOT_SAVED    136
#define IDR_MINIGAME_OBJ_NODE           137
#define IDC_LAST_NAIL_EXE               137
#define IDR_TRIGGERS_NODE               138
#define IDS_ANIM_WORK_TIME              138
#define IDS_NO_ANIM_WORK_TIME           139
#define IDR_STATIC_OBJS_NODE            140
#define IDS_SCALE_INFO_FORMAT           140
#define IDR_ANIMATED_OBJS_NODE          141
#define IDS_SCALE_COMBO_TOOLTIP_TEXT    141
#define IDR_MOVING_OBJS_NODE            142
#define ID_VIEW_SCENE_TOOLBAR           142
#define IDS_OBJECT_COLUMN               142
#define IDR_STATIC_OBJ_NODE             143
#define IDS_INTERF_SLDR_PURPOSE_SOUND_VOLUME 143
#define IDR_ANIMATED_OBJ_NODE           144
#define ID_VIEW_TE_TOOLBAR              144
#define IDS_ASK_SHOW_OBJECTS            144
#define IDR_MOVING_OBJ_NODE             145
#define IDS_ASK_REMOVE_ALL              145
#define IDR_ANIMATION_NODE              146
#define IDS_ASK_REMOVE_EDGES            146
#define IDR_TRIGGER_NODE                147
#define IDS_ANIMATION_EXT               147
#define IDR_MINIGAMES_NODE              148
#define IDS_CAP_ANIMATION_PHASE         148
#define IDD_DLG_DIR_SELECT              149
#define IDS_CLMN_ANIM_SPEED_NAME        149
#define IDR_NET_NODE                    150
#define ID_MR_L                         150
#define IDS_STRING150                   150
#define IDS_EVENT_MAIN_MENU             150
#define IDS_OPEN_MUSIC_TRACK_EXT        151
#define IDR_MUSIC_TRACKS_NODE           152
#define IDS_STRING152                   152
#define IDR_DEFAULT_FONT                153
#define IDC_ADD_MUSIC_TRACK             153
#define IDR_DEFAULT_CURSOR              154
#define IDC_MUSIC_TRACK_CYCLED          154
#define IDS_OPEN_PROJECT_FOR_JOIN_TITLE 154
#define IDR_DEFAULT_FONT_IDX            155
#define IDC_MUSIC_TRACK_STOP            155
#define IDS_SELECT_SCENES               155
#define IDR_GRID_ZONE_STATE_NODE        156
#define IDS_GAME_ENDS_NODE_NAME         156
#define IDI_MAIN_ICON                   157
#define IDR_MENU1                       157
#define IDS_WIZARD_CAP_ADD_GAME_END     157
#define IDI_MAIN_ICON_16_16             158
#define IDC_EDIT_STATE_ANIMATION        158
#define IDS_COND_TMPL_STATE_ANIM_PHASE  158
#define IDD_PROPPAGE_CHARACTER_BOUND    159
#define IDC_REMOVE_EDGES                159
#define IDR_MENU2                       160
#define IDR_MENU_FOR_BUTTONS            160
#define IDS_REG_VAL_NAME_ANIM_CADR_DUR  160
#define ID_GG_161                       161
#define IDS_SETTING_NAME_ANIM_CADR_DUR  161
#define IDC_REMOVE_EDGES_IN_STATES      162
#define IDS_SPRITE_EXT                  162
#define IDI_TE_ICON                     163
#define IDC_REMOVE_EDGES_FOR_ALL_OBJS   163
#define IDS_COND_TMPL_STATE_ANIM_PHASE_NOT 163
#define IDC_BIND_OBJ_CENTER             164
#define IDS_NO                          164
#define IDC_BACK_COLOR                  164
#define IDC_TE_LINK_TYPE0               165
#define IDS_COND_TMPL_OBJ_PREV_STATE    165
#define IDC_TE_LINK_TYPE1               166
#define IDS_COND_TMPL_OBJ_PREV_STATE_NOT 166
#define IDC_TE_LINK_TYPE2               167
#define IDS_REG_SEC_NAME_SV             167
#define IDC_TE_LINK_TYPE3               168
#define IDS_COND_TMPL_OBJ_PREV_STATE_EMPTY 168
#define IDC_TE_LINK_TYPE4               169
#define IDS_COUNTERS_NODE_NAME          169
#define IDC_TE_LINK_TYPE5               170
#define IDS_PPCAP_COUNTER_PROPERTIES    170
#define IDC_TE_LINK_TYPE6               171
#define IDS_NEW_COUNTER_NAME            171
#define IDC_TE_LINK_TYPE7               172
#define IDS_CLMN_INC_STATES             172
#define IDC_TE_LINK_TYPE8               173
#define IDS_CLMN_DEC_STATES             173
#define IDC_TE_LINK_TYPE9               174
#define IDS_CLMN_ALL_STATES             174
#define IDS_COND_TMPL_STATE_WORK_TIME_GREATER_WORK_TIME 175
#define IDD_DIALOG1                     176
#define IDD_DLG_CURSOR_PROP             176
#define IDS_COND_TMPL_STATE_WORK_TIME_GREATER_WORK_TIME_NOT 176
#define IDD_DLG_INVENTORY               177
#define IDS_COND_TMPL_STATE_WORK_TIME_IN_INTERVAL_NOT 177
#define IDS_COND_TMPL_STATE_WORK_TIME_IN_INTERVAL 178
#define IDD_DLG_NAME                    179
#define IDS_COND_TMPL_MOUSE_CLICK_NOT   179
#define IDD_DLG_STATE_PROP              180
#define IDB_GLOBAL_NODE                 180
#define IDS_COND_TMPL_MOUSE_OBJECT_CLICK_NOT 180
#define IDD_MOVING_LIST                 181
#define IDR_STATE_NODE                  181
#define IDB_LOCATIONS_NODE              181
#define IDS_COND_TMPL_OBJECT_IN_ZONE_NOT 181
#define IDD_PROPPAGE_OBJECT_PARALAX     182
#define IDB_LOCATON_NODE                182
#define IDS_COND_TMPL_STATIC_DIRECTION2_NOT 182
#define IDB_SCENES_NODE                 183
#define IDS_COND_TMPL_WALK_DIRECTION2_NOT 183
#define IDB_SCENE_NODE                  184
#define IDS_COND_TMPL_MOUSE_DLG_CLICK_NOT 184
#define IDB_NET_NODE                    185
#define IDS_COND_TMPL_MG_IN_STATE_NOT   185
#define IDB_STATIC_OBJS_NODE            186
#define IDS_FORMAT_STATE_PP_OBJ         186
#define IDB_ANIMATED_OBJS_NODE          187
#define IDS_COND_TMPL_STATE_WORK_TIME_GREATER_VALUE 187
#define IDB_MOVING_OBJS_NODE            188
#define IDS_COND_TMPL_STATE_WORK_TIME_GREATER_VALUE_NOT 188
#define IDB_MOUSE_NODE                  189
#define IDS_COND_TMPL_COUNTER_GREATER_COUNTER_NOT 189
#define IDB_TRIGGERS_NODE               190
#define IDS_COND_TMPL_COUNTER_GREATER_COUNTER 190
#define IDB_STATIC_OBJ_NODE             191
#define IDS_COND_TMPL_COUNTER_GREATER_VALUE_NOT 191
#define IDB_ANIMATED_OBJ_NODE           192
#define IDS_COND_TMPL_COUNTER_GREATER_VALUE 192
#define IDB_MOVING_OBJ_NODE             193
#define IDS_COND_TMPL_COUNTER_LESS_VALUE_NOT 193
#define IDB_STATE_NODE                  194
#define IDS_COND_TMPL_COUNTER_LESS_VALUE 194
#define IDB_TRIGGER_NODE                195
#define IDS_COND_TMPL_COUNTER_IN_INTERVAL_NOT 195
#define IDB_STATE_CATALOG               196
#define IDS_COND_TMPL_COUNTER_IN_INTERVAL 196
#define IDB_GLOBAL_STATE_NODE           197
#define IDS_EVENT_PLAY_VIDEO            197
#define IDB_CA_STATE_NODE               198
#define IDS_EVENT_BUTTON_STATE          198
#define IDB_GLOBAL_OBJ_STATE_NODE       199
#define IDS_EVENT_CLEAR_MOUSE           199
#define IDS_OPTION_SOUND                200
#define IDS_OPTION_SOUND_VOLUME         201
#define IDR_TOOLBAR_SCENE               202
#define IDC_CUR_PEN                     202
#define IDS_OPTION_MUSIC                202
#define IDR_INTERFACE_DISPATCHER        203
#define IDS_OPTION_MUSIC_VOLUME         203
#define IDD_DLG_COORD_ANIM              204
#define IDC_CREATE_ISCREEN              204
#define IDR_INTERFACE_SCREEN_NODE       205
#define IDS_OPTION_NONE                 205
#define IDD_DLG_GAME_SETTINGS           206
#define IDC_ADD_INTRF_BUTTON            206
#define IDS_COND_TMPL_OBJECT_ON_PERSONAGE_WAY_NOT 206
#define IDC_ADD_INTERF_BACKGROUND       207
#define IDS_COND_TMPL_OBJECT_ON_PERSONAGE_WAY 207
#define IDD_DLG_SCENE_LIST              208
#define IDC_ADD_INTERF_SLIDER           208
#define IDC_COND_TMPL_KEY_PRESSED       208
#define IDC_COND_TMPL_KEY_PRESSED_NOT   209
#define IDR_INTERFACE_ELE_NODE          210
#define IDS_MOVEMENT_LEFT               210
#define IDD_DLG_TRIG_DBG                211
#define IDS_MOVEMENT_UP                 211
#define IDR_MENU_PROF_DLG               212
#define IDS_MOVEMENT_RIGHT              212
#define ID_GG_213                       213
#define IDS_MOVEMENT_DOWN               213
#define IDD_PROPPAGE_AA_HOW             214
#define IDC_LOAD_DBG                    214
#define IDS_MOVEMENT_HORIZONTAL         214
#define IDC_CLEAR_DBG_LIST              215
#define IDS_MOVEMENT_VERTICAL           215
#define IDD_DLG_SEL_CATALOGS            216
#define ID_VIEW_TRIG_DBG_BAR            216
#define IDS_COND_TMPL_OBJECT_HIDDEN     216
#define IDD_PROPPAGE_MAKE_STATE         217
#define IDR_CO_DLG_MENU                 217
#define IDS_MOVEMENT_EIGHT_DIRS         217
#define IDD_DLG_STATE_COND              218
#define IDC_CREATE_OR                   218
#define IDS_MOVEMENT_SMOOTH             218
#define IDI_ICO_WARN                    219
#define IDC_CREATE_AND                  219
#define IDS_GAIT_ANGLE_FORMAT           219
#define IDI_ICO_ERR                     220
#define ID_GG_CREATEGROUP               220
#define IDS_COND_TMPL_ANY_PERSONGE_IN_ZONE_NOT 220
#define IDI_ICO_INFO                    221
#define IDC_CHANGE_TYPE                 221
#define IDS_COND_TMPL_ANY_PERSONGE_IN_ZONE 221
#define ID_GG_L                         222
#define IDS_CELLSET_TYPE_FORMAT         222
#define IDB_INFO                        223
#define IDC_DELETE                      223
#define IDS_CD_DISK_NAME_FORMAT         223
#define IDB_WARN                        224
#define IDC_REMOVE_FROM_GROUP           224
#define IDS_DISK_CONTENT_FORMAT         224
#define IDB_STOP                        225
#define IDS_DEL_CONDITION               225
#define IDR_MOVING_OBJ_GAITS_NODE       226
#define IDC_AUTO_RESTART                226
#define IDS_SCANE_FILES_PROGRESS_CAPTION 226
#define IDD_DLG_SCALE                   227
#define IDR_MOVING_OBJ_ANIMATION_NODE   227
#define IDC_MAKE_BOUND_AS_FIRST         227
#define IDS_DISK_CONTENT_COLUMN_CAPTION 227
#define IDC_PERS_DIM                    228
#define IDS_MOVEMENT_UP_LEFT            228
#define IDR_MENU3                       229
#define IDR_INTERF_EVENTS               229
#define IDS_MOVEMENT_UP_RIGHT           229
#define IDC_CUR_HAND                    230
#define IDC_ADD_EVENT                   230
#define IDS_MOVEMENT_DOWN_RIGHT         230
#define IDC_CUR_DRAG_HAND               231
#define IDC_REMOVE_EVENT                231
#define IDS_MOVEMENT_DOWN_LEFT          231
#define IDR_MOUSE_NODE                  232
#define IDC_ADD_INTERF_BTN_STATE        232
#define IDS_STATE_OWNER                 232
#define IDR_VIDEOS_NODE                 233
#define ID_Menu                         233
#define IDS_STRING233                   233
#define IDS_ADD_SUCCESSFUL              233
#define IDR_VIDEO_NODE                  234
#define ID_RR_234                       234
#define IDS_ADD_FAIL                    234
#define IDD_DLG_COND_MOUSE_CLICK        235
#define IDR_NET_GRID_ZONE_NODE          235
#define IDR_GRID_ZONE_NODE              235
#define IDC_ADD_INTERF_SAVE             235
#define IDS_PPCAP_MUSIC_TRACK_PROPERTIES 235
#define IDD_DLG_COND_MOUSE_OBJ_CLICK    236
#define IDC_CRT_ANIM_OBJ_BY_MASK        236
#define IDS_DIALOGS_FRAME_NODE_NAME     236
#define IDD_DLG_COND_MOVING_ON_NET      237
#define IDS_MOVOBJ_CATALOG              237
#define IDS_PPCAP_DIALOGS_FRAME_PROPERTIES 237
#define IDD_DLG_COND_OBJ_ON_NET         238
#define IDR_TOOLBAR_SCALE               238
#define IDS_TEXTDB_FILTER               238
#define IDD_DLG_COND_TIMER              239
#define IDS_OSD_CAP_SELECT_TEXTDB       239
#define IDD_DLG_COND_WALK_STOP_DIR      240
#define IDC_SCALE_MGR                   240
#define IDS_COND_TMPL_OBJECT_HIDDEN_NOT 240
#define IDC_DELETE_ALL                  241
#define IDS_DIALOG_EDITOR               241
#define IDD_DLG_SEL_ANIM_OBJ            242
#define IDR_MENU4                       242
#define IDR_BETWEEN_PLOTS_MENU          242
#define IDS_CNT_LOAD_MINI_GAME_EXE2     242
#define IDS_CNT_LOAD_DIALOG_EDITOR_EXE  242
#define IDC_INSERT_ROWS                 243
#define IDS_INI_SEC_NAME_TE             243
#define IDD_PROPPAGE_NET_ZONE           244
#define IDC_INSERT_COLUMNS              244
#define IDS_INI_KEY_NAME_VISIBLE_RECT_LEFT 244
#define IDD_SOUND_LIST                  245
#define IDC_CUR_FOOT                    245
#define IDC_CREATE_AND_FOR_ALL          245
#define IDS_INI_KEY_NAME_VISIBLE_RECT_TOP 245
#define IDC_CREATE_OR_FOR_ALL           246
#define IDS_INI_KEY_NAME_VISIBLE_RECT_RIGHT 246
#define IDD_DLG_APP_SETTINGS            247
#define IDC_DELETE_ROW                  247
#define IDS_INI_KEY_NAME_VISIBLE_RECT_BOTTOM 247
#define IDC_CUR_RESIZE                  248
#define IDC_DELETE_COLUMN               248
#define IDS_INI_KEY_NAME_LAST_TRIGGER_CHAIN 248
#define IDC_CUR_ROTATE                  249
#define IDC_CONVERT_TO_QDA              249
#define IDS_OSD_CAP_SELECT_TXT_FILE     249
#define ID_HH_REMOVEEDGES               250
#define IDS_STATE_IN_CONDITIONS         250
#define IDD_DLG_STACK_STATE_COORD       251
#define IDS_OBJECT_IN_CONDITIONS        251
#define IDD_DLG_NAMED_OBJECT_SELECTOR   252
#define IDS_REG_VAL_NAME_TE_SHOW_MENU_ON_LINK_CREATE 252
#define IDD_TRG_PROFILER_LEGEND         253
#define IDS_SETTING_NAME_TE_SHOW_MENU_ON_LINK_CREATE 253
#define IDR_GAME_ENDS_NODE              254
#define IDS_CD_KEY_WRONG_LEN            254
#define IDD_PROPPAGE_ANIM_OBJ_BOUND     255
#define IDC_ADD_GAME_END                255
#define IDS_INI_KEY_NAME_VISIBLE_CHAINS_RECTS 255
#define IDD_PROPPAGE_SELECT_INTERF_SCREEN 256
#define IDS_ASK_FOR_RENAME_INVENTORY    256
#define IDS_STRING257                   257
#define IDS_ALL_TRIGGER_CHAINS_NAME     257
#define IDC_TE_HILITE_LINKS             258
#define IDS_COND_TMPL_MOUSE_RIGHT_OBJECT_ZONE_CLICK 258
#define IDR_TE_TOOLBAR                  259
#define IDR_COUNTERS_NODE               259
#define IDS_COND_TMPL_MOUSE_RIGHT_OBJECT_ZONE_CLICK_NOT 259
#define IDC_CREATE_COUNTER              260
#define IDS_COND_TMPL_MOUSE_RIGHT_ZONE_CLICK 260
#define IDD_PO_PROPPAGE_TE_SETTINGS     261
#define IDS_COND_TMPL_MOUSE_RIGHT_ZONE_CLICK_NOT 261
#define IDD_DIALOG_MOVEMENT_TYPE        262
#define IDS_COND_TMPL_MOUSE_RIGHT_OBJECT_CLICK 262
#define ID_XM_MOVEMENTTYPE              263
#define IDS_COND_TMPL_MOUSE_RIGHT_OBJECT_CLICK_NOT 263
#define IDC_SELECT_MOVEMENT_TYPE        264
#define IDS_COND_TMPL_MOUSE_HOVER       264
#define IDB_BMP_ITEM_STATE_STATE_IN_TGR 265
#define IDD_DLG_ACCELERATION_MAX_SPEED  265
#define IDS_COND_TMPL_MOUSE_HOVER_NOT   265
#define IDB_BMP_ITEM_STATE_NULL_BMP     266
#define IDD_DIALOG2                     266
#define IDD_DLG_DISK_SORT               266
#define IDS_COND_TMPL_MOUSE_OBJECT_HOVER 266
#define IDR_TE_LINK                     267
#define IDB_BMP_ITEM_STATE_OBJ_VISIBLE  267
#define IDS_COND_TMPL_MOUSE_OBJECT_HOVER_NOT 267
#define IDR_TE_TRIGGER_ELE              268
#define IDB_BMP_ITEM_STATE_OBJ_NOT_VISIBLE 268
#define IDS_COND_TMPL_MOUSE_ZONE_HOVER  268
#define IDR_GLOBAL_MOVING_OBJ_NODE      269
#define IDB_INVENTORY_STATE_NODE        269
#define IDS_COND_TMPL_MOUSE_ZONE_HOVER_NOT 269
#define IDB_DIALOG_STATE_NODE           270
#define IDR_CD_MNGR_TREE_MENU           270
#define IDS_COND_TMPL_MOUSE_OBJECT_ZONE_HOVER 270
#define IDD_DLG_STATE_BOUND             271
#define IDB_MINIGAME_NODE               271
#define ID_CD_DISK_MNGR_ADDCD           271
#define IDS_COND_TMPL_MOUSE_OBJECT_ZONE_HOVER_NOT 271
#define IDB_MINIGAMESTATE_NODE          272
#define ID_CD_DISK_MNGR_REMOVECD        272
#define IDS_COND_MOUSE_HOVER_OBJ_SELF   272
#define IDD_DLG_ASK                     273
#define IDB_MINIGAMES_NODE              273
#define ID_CD_DISK_MNGR_REMOVE          273
#define IDS_MOUSE_CLICK_ON              273
#define IDR_INVENTORY_OBJS_NODE         274
#define IDB_MUSIC_TRACKS_NODE           274
#define ID_MANAGE_CDS                   274
#define IDS_MOUSE_HOVER                 274
#define IDR_INVENTORY_OBJ_NODE          275
#define IDB_MUSIC_TRACK_NODE            275
#define IDS_COND_TMPL_MOUSE_RIGHT_CLICK 275
#define IDD_PROPPAGE_INVENTORY          276
#define IDB_GZONE_STATE_NODE            276
#define IDS_COND_TMPL_MOUSE_RIGHT_CLICK_NOT 276
#define IDD_PROPPAGE_INVENTORY_FOR_PERS 277
#define IDR_MUSIC_TRACK_NODE            277
#define IDB_INTERFACE_NODE1             277
#define IDB_INTERFACE_NODE              277
#define IDS_SET_OBJECT                  277
#define IDD_DLG_ADD_CELL_SET            278
#define IDB_INTERFACE_SCREEN_NODE       278
#define IDR_INTERFACE_ELE_STATE_NODE    278
#define IDS_OBJECT_ON                   278
#define IDD_DLG_COND_MOUSE_DLG_CLICK    279
#define IDB_INTERFACE_NODE2             279
#define IDB_INTERFACE_ELEMENT_NODE      279
#define IDR_INTERFACE_BTN_NODE          279
#define IDS_COND_DLG_OBJ_ZONE_HOVER_STATIC_CAP 279
#define IDB_CURSOR_FOR_DYN_OBJ          280
#define IDR_GAME_END_NODE               280
#define IDD_DLG_OBJECT_LIST             280
#define IDS_COND_DLG_MOUSE_OBJ_HOVER_OBJECT_STATIC_CAP 280
#define IDD_PAGE_SELECT_FILES           281
#define IDB_CURSOR_FOR_ZONES            281
#define IDR_INTERFACE_BACK_NODE         281
#define IDS_COND_DLG_MOUSE_OBJ_XXX_OBJECT_STATIC_1_CAP 281
#define IDB_CURSOR_FOR_DYN_OBJ1         282
#define IDB_CURSOR_FOR_DYN_OBJ_AND_ZONES 282
#define IDR_TE_TRIGGER_ELE1             282
#define IDS_INTERF_EVENT_DESCR_LOAD_SCENE 282
#define IDD_PROPPAGE_ADD_ANIM_1         283
#define IDB_CURSOR_NODE                 283
#define IDR_COUNTERS_NODE1              283
#define IDR_COUNTER_NODE                283
#define IDS_FORMAT_STATE_PP_OBJ2        283
#define IDB_GZONE_NODE                  284
#define IDR_CD_MNGR_TREE_MENU1          284
#define IDS_DEFAULT_TEXT_WINDOW_NAME    284
#define IDD_PROPPAGE_AA_SEL_EXIST       285
#define IDB_VIDEO_NODE                  285
#define IDR_DIALOG_FRAME                285
#define IDS_INTERF_TEXT_WINDOW_PROPERTIES 285
#define IDD_PROPPAGE_CONVERT_WAY        286
#define IDB_VIDEOS_NODE                 286
#define IDR_INTERFACE_TEXT_WINDOW_NODE  286
#define IDS_INI_KEY_NAME_SHOW_TRIGGER   286
#define IDD_DLG_CO_CONDS                287
#define IDB_INVENTORY_OBJS_NODE         287
#define IDS_FONTS_CATALOG               287
#define IDR_FONTS_NODE                  287
#define IDD_DLG_COND_MG_IN_STATE        288
#define IDB_INVENTORY_OBJ_NODE          288
#define IDR_FONT_NODE                   288
#define IDS_DEFAULT_FONT                288
#define IDD_PROPPAGE_AA_DONE            289
#define IDB_NOT_MOV_STATIC_OBJ_NODE     289
#define IDD_PROPPAGE_IELE_ADD_DONE      289
#define IDS_OPEN_FONT_FILE_TITLE        289
#define IDD_PROPPAGE_CONVERT_WAY1       290
#define IDD_PROPPAGE_CREATE_OBJ         290
#define IDB_DISABLE_MOUSE_ANIMATED_OBJ_NODE 290
#define IDS_PPCAP_FONT_PROPERTIES       290
#define IDD_PROPPAGE_MDS_SELECT_FOLDER  291
#define IDS_ERROR_CANT_LOAD_FONT        291
#define IDD_PROPPAGE_MDS_SCENE_COUNT    292
#define IDB_BMP_ITEM_STATE_STATE_IN_TGR1 292
#define IDB_BMP_ITEM_STATE_STATE_IN_NOT_ACTIVE_TGR 292
#define IDC_ERROR_COPING_FAILED         292
#define IDD_PROPPAGE_MDS_PROGRES        293
#define IDB_CURSOR_FOR_ALL_NODE         293
#define IDS_MOUSE_CLICK_FAILED          293
#define IDD_PROPPAGE_AA_DONE1           294
#define IDD_PROPPAGE_MDS_DONE           294
#define IDB_GZONE_NEED_CUR_NODE         294
#define IDS_MOUSE_OBJECT_CLICK_FAILED   294
#define IDD_PROPPAGE_AA_CADR_PAUSE      295
#define IDB_STATE4INVENTORY_NODE        295
#define IDS_MOUSE_CLICK_FAILED_NOT      295
#define IDD_DLG_COND_OBJ_IN_STATE       296
#define IDB_TO_BEGIN                    296
#define IDS_MOUSE_OBJECT_CLICK_FAILED_NOT 296
#define IDD_PROPPAGE_VIDEO              297
#define IDB_TO_END                      297
#define IDS_SETTING_NAME_NET_SCALE_POW  297
#define IDD_PROPPAGE_INVENTORY_PROPS    298
#define IDB_NEXT                        298
#define IDS_REG_VAL_NAME_NET_SCALE_POW  298
#define IDD_DLG_COND_OBJ_DISTANCE       299
#define IDB_PREV                        299
#define IDS_SETTING_NAME_NET_SCALE_Z_OFFSET 299
#define IDD_DLG_COND_MOVING_ACITVE      300
#define IDB_CURSOR_FOR_MAIN_MENU        300
#define IDS_REG_VAL_NAME_NET_SCALE_Z_OFFSET 300
#define IDD_PROPPAGE_INTRF_ELE_POS      301
#define IDB_CURSOR_FOR_INGAME_INTERF    301
#define IDS_SELF_RELATIVE               301
#define IDD_INTRF_ELE_STATE_PROP        302
#define IDB_GAME_END_NODE               302
#define IDS_MOUSE_CLICK_EVENT_TEXT      302
#define IDD_PROPPAGE_SELECT_NAME        303
#define IDB_GAME_ENDS_NODE              303
#define IDS_MOUSE_OBJECT_CLICK_EVENT_TEXT 303
#define IDD_PROPPAGE_SEL_ANIM_AND_SOUND 304
#define IDB_COUNTER_NODE                304
#define IDS_MOUSE_RIGHT_CLICK_EVENT_TEXT 304
#define IDD_PROPPAGE_AA_DONE2           305
#define IDB_COUNTERS_NODE               305
#define IDS_MOUSE_RIGHT_OBJECT_CLICK_EVENT_TEXT 305
#define IDD_PROPPAGE_INTRF_BACK_PROP    306
#define IDB_COUNTER_TREE_BMP            306
#define IDS_NOT_FOUND                   306
#define IDD_PROPPAGE_INTRF_SAVE_PROP    307
#define IDB_CD                          307
#define IDS_INFORMATION                 307
#define IDD_PROPPAGE_INTRF_SLIDER       308
#define IDB_VIDEO_NOT_IN_CD             308
#define IDS_COND_TMPL_MOUSE_STATE_PHRASE_CLICK 308
#define IDD_PROPPAGE_INTRF_SLIDER_STATE 309
#define IDB_SCENE_NOT_IN_CD             309
#define IDS_COND_TMPL_MOUSE_STATE_PHRASE_CLICK_NOT 309
#define IDD_DLG_SCALE_MGR               310
#define IDB_DIALOGS_FRAME_NODE          310
#define IDS_COND_TMPL_OBJECT_IS_CLOSER  310
#define IDD_DLG_COND_ANIM_PHASE         311
#define IDB_FONTS_NODE                  311
#define IDS_COND_TMPL_OBJECT_IS_CLOSER_NOT 311
#define IDD_PO_PROPPAGE_SCENE_SETTINGS  312
#define IDB_FONT_NOT_IN_CD              312
#define IDS_CLMN_SOUND_FREQUENCY_NAME   312
#define IDD_PROPPAGE_GAME_SETTINGS4START_WIZARD 313
#define IDB_FONT_NODE                   313
#define IDS_STRING313                   313
#define IDS_PPCAP_FONTS_PROPERTIES      313
#define IDD_PROPPAGE_COUNTER            314
#define IDB_CURSOR_FOR_ZONES1           314
#define IDB_CURSOR_FOR_OBJ_IN_INVENTORY 314
#define IDS_COND_TMPL_MOUSE_OBJECT_CLICK_EVENT_TEXT 314
#define IDD_DLG_COND_WORK_TIME_GREATE_WORK_TIME 315
#define IDB_INTERFACE_ELEMENT_STATE_NODE1 315
#define IDB_INTERFACE_ELEMENT_STATE_NODE 315
#define IDS_COND_TMPL_MOUSE_RIGHT_OBJECT_CLICK_EVENT_TEXT 315
#define IDD_DLG_COND_WORK_TIME_GREATER_VALUE 316
#define IDS_TMPL_MG_PARAM_OBJECT        316
#define IDD_DLG_COND_WORK_TIME_IN_INTERVAL 317
#define IDS_PARAM_NAME_COLUMN           317
#define IDD_DLG_COND_COUNTER_GREATER_COUNTER 318
#define IDS_PARAM_VALUE_COLUMN          318
#define IDD_DLG_COND_COUNTER_LESS_GREATER_VALUE 319
#define IDS_PARAM_COMMENT_COLUMN        319
#define IDD_DLG_COND_COUNTER_IN_INTERVAL 320
#define IDS_PPCAP_MINIGAME_PROPERTIES   320
#define IDD_PROPPAGE_INTRF_SCREEN       321
#define IDS_OPEN_ALL_FILES_FILTER       321
#define IDD_PROPPAGE_INTRF_BTN_PROP     322
#define IDS_NOT_SELECTED                322
#define IDD_DLG_COND_OBJ_ON_PERSONAGE_WAY 323
#define IDS_EXPAND_KEY                  323
#define IDD_PROPPAGE_MOVING_OBJ_CONTROL 324
#define IDS_STRING324                   324
#define IDS_INI_KEY_NAME_FOCUSED_NODE   324
#define IDD_DLG_COND_KEYPRESSED         325
#define IDS_COND_TMPL_ANIM_OBJ_IDLE_GRT_THAN_VAL 325
#define IDD_DLG_COND_ANY_MOVING_ON_NET  326
#define IDS_COND_TMPL_ANIM_OBJS_INTERS_BOUNDS 326
#define IDD_PROPPAGE_MUSIC_TRACK        327
#define IDS_COND_TMPL_ANIM_OBJS_INTERS_BOUNDS_NOT 327
#define IDD_PROPPAGE_SCREEN_TEXT        328
#define IDS_OPEN_PROFILER_FILE_TITLE    328
#define IDD_PROPPAGE_INTRF_TEXT_WINDOW  329
#define IDS_OPEN_PROFILER_FILE_FILTER   329
#define IDD_DLG_SELECT_TEXT_ID          330
#define IDS_OPEN_PROFILER_FILE_EXT      330
#define IDD_PROPPAGE_FONT               331
#define IDS_EVENT_SCROLL_LEFT           331
#define IDD_DLG_COND_MOUSE_STATE_PHRASE_CLICK 332
#define IDS_EVENT_SCROLL_RIGHT          332
#define IDR_ELEMENT_STATE_MODE          333
#define IDD_DLG_COND_OBJECT_IS_CLOSER   333
#define IDS_EVENT_SCROLL_UP             333
#define IDD_PROPPAGE_FONTS              334
#define IDS_EVENT_SCROLL_DOWN           334
#define IDR_INTERFACE_COUNTER_NODE      334
#define IDD_DIALOG_MINIGAME_PARAMS      335
#define IDS_COLLECT_EXTERNAL_FILES      335
#define IDD_DIALOG_SEL_OBJ_NAME         336
#define IDS_SCRIPT_SAVING               336
#define IDD_PROPPAGE_MINIGAME           337
#define IDS_COND_LIST_SETUP_FILE        337
#define IDS_CONDITION_LIST_SETUP_FILE   337
#define IDS_EVENT_SHOW_INTERFACE_SCREEN_AS_MODAL 338
#define IDS_EVENT_MODAL_OK              339
#define IDD_DLG_COND_ANIM_OBJ_IDLE_GRT_VAL 340
#define IDS_EVENT_MODAL_CANCEL          340
#define IDS_NEW_FONT_NAME               341
#define IDS_TEXT_ALIGN_LEFT             342
#define IDR_HTML_ANIMOBJIDLECONDDLG     343
#define IDS_TEXT_ALIGN_CENTER           343
#define IDD_DLG_COND_TWO_OBJ_BASE       344
#define IDS_TEXT_ALIGN_RIGHT            344
#define IDD_INTRF_ELE_STATE_PROP1       345
#define IDD_INTRF_BTN_STATE             345
#define IDS_LOAD                        345
#define IDS_SAVE                        346
#define IDS_TWO_TRIGGERS_NEEDED         347
#define IDD_DLG_CONDITION_LIST          348
#define IDS_OFF                         348
#define IDS_DEFAULT_INTERF_COUNTER_NAME 349
#define IDS_INTERF_BACK_PROPERTIES2     350
#define IDS_INTERF_COUNTER_PROPERTIES   350
#define IDD_PROPPAGE_INTRF_COUNTER_PROP 351
#define IDS_CLMN_STARTS                 351
#define IDB_BMP_ITEM_STATE_DEF_STATE    352
#define IDS_STRING352                   352
#define IDS_CLMN_ENDS                   352
#define IDS_CLMN_EXECUTE_TYPE           353
#define IDS_EXECUTE_CLICK               354
#define IDS_EXECUTE_HOVER               355
#define IDS_WINDOW_DIALOGS              356
#define IDS_WINDOW_EDIT                 357
#define IDS_WINDOW_TEXT                 358
#define IDS_INFO_PLAYER_NAME            359
#define IDS_INFO_NONE                   360
#define IDS_INFO_PLAYER_SCORE           361
#define IDS_VALIGN_TOP                  362
#define IDS_VALIGN_CENTER               363
#define IDS_VALIGN_BOTTOM               364
#define IDC_SPIN1                       1000
#define IDC_RADIO_CONV                  1000
#define IDC_SPIN2                       1001
#define IDC_LIST_VARS                   1002
#define IDC_SPIN3                       1002
#define IDC_CHECK_USE_ORIENTATION       1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_SPIN4                       1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_EDIT_DIRECTION              1004
#define IDC_SPIN_SCALE_POW              1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_EDIT_X                      1005
#define IDC_SPIN_DIR                    1005
#define IDC_BUTTON_VAR_ADD2             1006
#define IDC_EDIT_Y                      1006
#define IDC_EDIT_ROTATEX                1006
#define IDC_EDIT_X2                     1006
#define IDC_BUTTON_VAR_EDIT2            1007
#define IDC_RADIO_NO_GAIT               1007
#define IDC_EDIT_Z_                     1007
#define IDC_EDIT_SCR_X                  1007
#define IDC_SLIDER_CA_ANIM_SCROLLER     1007
#define IDC_EDIT_D                      1007
#define IDC_BUTTON_VAR_DEL              1008
#define IDC_RADIO_GAIT                  1008
#define IDC_EDIT_SCR_Y                  1008
#define IDC_EDIT_ROTATEY                1008
#define IDC_PROGRESS                    1008
#define IDC_SLIDER_CA_ANIM_SCROLLER2    1008
#define IDC_EDIT_DIGITS                 1008
#define IDC_BUTTON_VAR_CREAT            1009
#define IDC_EDIT_HEIGHT                 1009
#define IDC_EDIT_SCR_D                  1009
#define IDC_BTN_STOP                    1009
#define IDC_EDIT_X3                     1009
#define IDC_RADIO_HEIHT                 1010
#define IDC_EDIT_Y2                     1010
#define IDC_EDIT_NET_PROJ_SCR_D         1010
#define IDC_EDIT_CX                     1010
#define IDC_STATIC_Z                    1011
#define IDC_EDIT_ROTATEZ                1012
#define IDC_CHECK_TOGETHER              1012
#define IDC_COMBO_SCENES                1013
#define IDC_STATIC_Z2                   1013
#define IDC_EDIT_CY                     1013
#define IDC_EDIT_FOCUS                  1014
#define IDC_STATIC_SCENE                1014
#define IDC_CHECK_SYNC_WITH_SOUND       1015
#define IDC_STATIC_SCENE2               1015
#define IDC_EDIT_Z_OFFSET               1015
#define IDC_COMBO_MGS                   1016
#define IDC_COMBO_SCENES2               1016
#define IDC_EDIT_CELLSIZE               1018
#define IDC_STATIC_SCROLL               1018
#define IDC_STATIC_H                    1019
#define IDC_STATIC_SCROLL2              1019
#define IDC_EDIT_CELLSX                 1020
#define IDC_FLAG_LOOP                   1021
#define IDC_EDIT                        1021
#define IDC_FLAG_FLIP_HORZ              1022
#define IDC_EDIT_XBOUND                 1022
#define IDC_EDIT_CELLSY                 1022
#define IDC_RADIO_NOT_CREATE            1022
#define IDC_BUTTON_RESET                1023
#define IDC_BUTTON_ADD_COND             1023
#define IDC_EDIT_YBOUND                 1023
#define IDC_RADIO_CREATE                1023
#define IDC_EDIT_Z                      1024
#define IDC_SPIN_X                      1024
#define IDC_FLAG_FLIP_VERT              1024
#define IDC_SPIN_Y                      1025
#define IDC_CHECK_INVENTORY             1025
#define IDC_SPIN5                       1025
#define IDC_BUTTON                      1025
#define IDC_SPIN_Z                      1026
#define IDC_BUTTON_UNDO                 1026
#define IDC_SPIN                        1026
#define IDC_SPIN_D                      1026
#define IDC_COMBO_CONDITION             1027
#define IDC_SPIN6                       1027
#define IDC_EDIT_PAUSE                  1027
#define IDC_SPIN_CX                     1027
#define IDC_SPIN_DIGITS                 1027
#define IDC_COMBO_OBJECT                1028
#define IDC_SPIN7                       1028
#define IDC_RADIO_CONVERT4              1028
#define IDC_SPIN_CY                     1028
#define IDC_COMBO_OBJECT2               1029
#define IDC_COMBO_CHARACTER             1029
#define IDC_EDIT6                       1029
#define IDC_SPIN8                       1029
#define IDC_CHECK_ENABLE_INTERRUPT      1029
#define IDC_DIR_SET                     1030
#define IDC_COMBO_ZONE                  1030
#define IDC_ADD_STATE                   1030
#define IDC_SELECT_BTN                  1030
#define IDC_STATIC_2                    1030
#define IDC_EDIT_SCALE_POW              1030
#define IDC_COMBO_PERS                  1031
#define IDC_COMBO_STATES                1031
#define IDC_COMBO_INVENTORY             1031
#define IDC_CHANGE_STATE                1031
#define IDC_SPIN_Z_OFFSET               1031
#define IDC_COMBO_OBJECT3               1031
#define IDC_COMBO_DIR                   1032
#define IDC_COMBO_CUR_STATE_ANIM        1032
#define IDC_LIST1                       1032
#define IDC_COMBO_CAMERA_MODE           1032
#define IDC_STATIC_3                    1032
#define IDC_DEL_STATE                   1033
#define IDC_COMBO_GAITS                 1033
#define IDC_CHECK_SET_POINTS            1034
#define IDC_EDIT_CAM_MODE_WORK_TIME     1034
#define IDC_EDIT_CAM_MODE_SCROLL_SPEED  1035
#define IDC_EDIT_CAM_MODE_SCROLL_DISTANCE 1036
#define IDC_EDIT_SX                     1037
#define IDC_EDIT_ANGLE                  1037
#define IDC_Z_EDIT                      1037
#define IDC_EDIT_START_DELAY            1037
#define IDC_EDIT_LONG_TEXT              1037
#define IDC_EDIT_AS_PERIOD              1037
#define IDC_EDIT_SCROLL_SPEED           1037
#define IDC_EDIT_SY                     1038
#define IDC_EDIT_STATE_DURATION         1038
#define IDC_EDIT_SCROLL_DIST            1038
#define IDC_Z_EDIT2                     1038
#define IDC_EDIT_ANGLE_SP               1038
#define IDC_EDIT_DURATION               1039
#define IDC_EDIT_ZBOUND                 1039
#define IDC_SPIN_DIST                   1039
#define IDC_EDIT_TEXT_DX                1039
#define IDC_EDIT_SCALE_X                1039
#define IDC_SPIN_DURATION               1040
#define IDC_COMBO_CURSOR                1040
#define IDC_EDIT_TEXT_DY                1040
#define IDC_EDIT_RND                    1041
#define IDC_EDIT_VIDEO_FILE             1041
#define IDC_COMBO_SAVE_MODE             1041
#define IDC_SPIN_RND                    1042
#define IDC_BTN_SELECT_VFILE            1042
#define IDC_EDIT_SCALE_X_SP             1042
#define IDC_EDIT_SPEED                  1043
#define IDC_EDIT_BACK_FILE              1043
#define IDC_SPIN_SPEED                  1044
#define IDC_SPIN_WX                     1044
#define IDC_BTN_SELECT_BFILE            1044
#define IDC_SPIN_WY                     1045
#define IDC_EDIT_SCALE_Y                1045
#define IDC_SPIN_WZ                     1046
#define IDC_CHECK_TO_CENTER             1046
#define IDC_SPINSX                      1046
#define IDC_EDIT_SCALE_Y_SP             1046
#define IDC_SPIN_SX                     1047
#define IDC_CHECK_FULL_SCREEN           1047
#define IDC_STATIC_DURATION             1047
#define IDC_SPINSY                      1047
#define IDC_SPIN_SY                     1048
#define IDC_CHECK3                      1048
#define IDC_CHECK_NO_INTERRUPT          1048
#define IDC_STATIC_5                    1048
#define IDC_CHECK_ACTIVE_CLICK_REACTING 1048
#define IDC_CHECK_IS_GLOBAL             1048
#define IDC_SPIN_SZ                     1049
#define IDC_STATIC_6                    1049
#define IDC_CHECK_VIDEO_INTRO           1049
#define IDC_SPIN_TEXT_DX                1049
#define IDC_EDIT_SCALE                  1050
#define IDC_CHECK_ENABLE_MUSIC          1050
#define IDC_SPIN_TEXT_DY                1050
#define IDC_COMBO_CURSORS               1051
#define IDC_SPIN_SZ2                    1051
#define IDC_SPIN_NET_PROJ_SCR_D         1051
#define IDC_RADIO_TO_CENTER             1052
#define IDC_RADIO_VERT_TO_CENTER        1053
#define IDC_EDIT_SCR_TEXT               1054
#define IDC_CHECK_FOR_DYN_OBJ           1055
#define IDC_CHECK_NEED_CURSOR           1055
#define IDC_CHECK_FOR_ZONES             1056
#define IDC_EDIT_DISTANCE               1057
#define IDC_CHECK_FOR_MAIN_MENU         1057
#define IDC_TREE                        1058
#define IDC_SPIN_DISTANCE               1058
#define IDC_EDIT_NAME                   1059
#define IDC_CHECK_SOUND_LOOP            1059
#define IDC_COMBO_ANIMATION             1061
#define IDC_CHECK_LEFT_TOP              1061
#define IDC_COMBO_SOUND                 1062
#define IDC_COMBO_MODES                 1062
#define IDC_CHECK_LEFT_TOP2             1062
#define IDC_LIST                        1063
#define IDC_STATIC_VIEW                 1064
#define IDC_EDIT_ANIM_FILE              1064
#define IDC_EDIT_DIR                    1065
#define IDC_BTN_SEL_ANIM                1065
#define IDC_CHECK_SHOW                  1066
#define IDC_CHECK_HORZ_INV              1066
#define IDC_STATIC_ANIM                 1067
#define IDC_CHECK_VERT_INV              1067
#define IDC_SPIN_CAM_PITCH              1068
#define IDC_EDIT_SOUND_FILE             1068
#define IDC_EDIT_CAM_PITCH              1069
#define IDC_BTN_SEL_SOUND               1069
#define IDC_SPIN_GRID_SIZE              1070
#define IDC_EDIT_GRID_SIZE              1071
#define IDC_COMBO_ACTION                1071
#define IDC_BTN_COLOR                   1072
#define IDC_EDIT_CAM_FOCUS              1073
#define IDC_STATIC_MSG                  1073
#define IDC_STATIC_GRID_COLOR           1074
#define IDC_EDIT_ANIM                   1074
#define IDC_SPIN_CAM_FOCUS              1075
#define IDC_STATIC_SOUND                1075
#define IDC_SPIN_PERS_HEIGHT            1076
#define IDC_SCROLLBAR                   1076
#define IDC_EDIT_PERS_HEIGHT            1077
#define IDC_EDIT1                       1077
#define IDC_BTN_BACK_COLOR              1078
#define IDC_EDIT_AR_SY                  1078
#define IDC_EDIT2                       1078
#define IDC_STATIC_BACK_COLOR           1079
#define IDC_CHECK2                      1079
#define IDC_CHECK_SMOOTH_SWITCH         1079
#define IDC_CHECK_AVOID_COLLISION       1079
#define IDC_SHORT_PHRASE_ID             1079
#define IDC_CHECK_RESET_TRIGGERS_ON_LOAD 1079
#define IDC_CHECK_NEED_SAVE_TIME_SHOW   1079
#define IDC_CHECK_FLIP_HORZ             1080
#define IDC_CHECK_AUTO_MOVE             1080
#define IDC_EDIT_BACK                   1080
#define IDC_CHECK_NEED_SAVE_SCREENSHOT  1080
#define IDC_CHECK_PERSONAGE_SWITCH      1080
#define IDC_CHECK_LOOP                  1081
#define IDC_CHECK_CLEAR_PATH            1081
#define IDC_CHECK_NEED_SAVE_NAME_SHOW   1081
#define IDC_EDIT_TEXT                   1081
#define IDC_CHECK_PERSONAGE_SWITCH2     1081
#define IDC_CHECK_MANIMENU_EXIT         1081
#define IDC_CHECK_FLIP_VERT             1082
#define IDC_RESOLUTION                  1082
#define IDC_CHECK_FOLLOW_ACTIVE_PERSONAGE 1083
#define IDC_RADIO_EXIST                 1084
#define IDC_STATIC1                     1084
#define IDC_CHECK_REPEAT_ACTIVE_PERSONAGE_MOVEMENT 1084
#define IDC_RADIO_CONVERT_FOR_SCENE     1085
#define IDC_STATIC2                     1085
#define IDC_RADIO_CONV_DISP             1086
#define IDC_STATIC3                     1086
#define IDC_CHECK_CONTROL_ATTACHMENT    1086
#define IDC_RADIO_CONV_DISP2            1087
#define IDC_STATIC4                     1087
#define IDC_RADIO_CONV_DISP3            1088
#define IDC_ORI_HORZ                    1088
#define IDC_CHECK_CONTROL_ATTACHMENT_WITHOUT_DIR_REL 1088
#define IDC_ORI_VERT                    1089
#define IDC_CHECK_CONTROL_ATTACHMENT3   1089
#define IDC_CHECK_CONTROL_ATTACHMENT_TO_ACTIVE_WITH_MOVING 1089
#define IDC_BUTTON1                     1090
#define IDC_COMBO_SCREEN                1090
#define IDC_COMBO_TARGET                1091
#define IDC_BTN_PREV                    1091
#define IDC_BUTTON_DEL_INC              1091
#define IDC_EDIT_AR_SX                  1092
#define IDC_BTN_NEXT                    1092
#define IDC_BUTTON_DEL_DEC              1092
#define IDC_SPIN_AR_SX                  1093
#define IDC_BTN_TO_END                  1093
#define IDC_BUTTON_SEL_BACKGROUND       1093
#define IDC_SPIN_AR_SY                  1094
#define IDC_STATIC_OFFSET               1095
#define IDC_COMBO_SCR_FOR_INV           1096
#define IDC_BTN_ADD_STATE               1097
#define IDC_COMBO_SCR_WITHOUT_INV       1097
#define IDC_STATIC_ANIM_TIME            1098
#define IDC_COMBOBOXEX_LOG              1099
#define IDC_EDIT_SAVEID                 1099
#define IDC_COMBO_SCR_WITHOUT_INV2      1099
#define IDC_COMBO_SAVE_PROMPT_SCR       1099
#define IDC_BTN_RUN                     1100
#define IDC_SPIN_SAVEID                 1100
#define IDC_COMBO_SAVE_NAME_SCR         1100
#define IDC_EDIT_OBJ_NAME               1101
#define IDC_COMBO_SCALES                1101
#define IDC_USE_LEFT_TOP                1102
#define IDC_ANIM_PHASE                  1102
#define IDC_BTN_COND                    1103
#define IDC_BTN_TO_BEG                  1103
#define IDC_CHECK_FOR_INGAME_INTERF     1104
#define IDC_USE_LEFT_TOP2               1104
#define IDC_FIXED_SCREEN_COORDS         1104
#define IDC_CHECK1                      1105
#define IDC_CHECK_CANT_INTERRUPT_MOVING 1105
#define IDC_CHECK_MOUSE_CONTROL         1105
#define IDC_CHECK_CYCLEX                1105
#define IDC_CHECK_TAKE_TO_MOUSE         1105
#define IDC_CHECK_ONLY_POSITIVE         1105
#define IDC_CHECK_LOAD_TO_MEMORY        1105
#define IDC_CHECK_SHOW_MENU_ON_LINK_CREATE 1105
#define IDC_CHECK_FOR_OBJ_IN_INVENTORY  1105
#define IDC_CHECK_NEED_SCENE_REDRAW     1105
#define IDC_CHECK_MUSIC_TRACK_CYCLED    1105
#define IDC_CHECK_FILL                  1105
#define IDC_CHECK_INVERSE_DIRECTION     1105
#define IDC_CHECK_AUTOSAVE              1105
#define IDC_STATIC_DONED_LINK           1106
#define IDC_CHECK_KEYBOARD_CONTROL      1106
#define IDC_STATIC_ACTIVE_LINK          1107
#define IDC_CHECK_COLLISION_CONTROL     1107
#define IDC_CHECK_PUT_TO_INVERNTORY_BY_RCLICK 1107
#define IDC_STATIC_INACTIVE_LINK        1108
#define IDC_CHECK_DONT_OPEN_AFTER_TAKE  1108
#define IDC_EDT_CUR_POINT               1109
#define IDC_STATIC_DONED_ELE            1109
#define IDC_CHECK_PUT_OBJECT_AFTER_CLICK 1109
#define IDC_SPIN_CUR_POINT              1110
#define IDC_STATIC_ACTIVE_ELE           1110
#define IDC_CHECK_VISIBLE_WHEN_INACTIVE 1110
#define IDC_SPIN_PHASA                  1111
#define IDC_STATIC_INACTIVE_ELE         1111
#define IDC_EDT_PHASE                   1112
#define IDC_STATIC_WAITING_ELE          1112
#define IDC_BTN_SHOW_LEGEND             1113
#define IDC_COMBO1                      1114
#define IDC_COMBO2                      1115
#define IDC_COMBO_SECOND_STATE          1115
#define IDC_COMBO_FONT                  1115
#define IDC_COMBO3                      1116
#define IDC_COMBO_FIRST_STATE_SCENE     1116
#define IDC_COMBO_FONT2                 1116
#define IDC_BUTTON_UP                   1117
#define IDC_COMBO4                      1117
#define IDC_COMBO_SECOND_STATE_SCENE    1117
#define IDC_COMBO_ATTACHER              1117
#define IDC_COMBO_SAVE_FONT             1117
#define IDC_BUTTON_LEFT                 1118
#define IDC_BUTTON_FAST_UP              1118
#define IDC_COMBO_ALIGN2                1118
#define IDC_BUTTON_RIGHT                1119
#define IDC_EDIT_BEG_PHASE              1119
#define IDC_BUTTON_DOWN                 1120
#define IDC_SPIN_BEG_PHASE              1120
#define IDC_EDIT_END_PHASE              1121
#define IDC_BUTTON_FAST_DOWN            1121
#define IDC_EDIT_HOZ_OFFSET             1122
#define IDC_SPIN_END_PHASE              1122
#define IDC_EDIT_VERT_OFFSET            1123
#define IDC_SPIN_SOUND                  1123
#define IDC_CHECK_CRT_OBJ               1124
#define IDC_SPIN_SOUND2                 1124
#define IDC_SPIN_FADE                   1124
#define IDC_CUSTOM1                     1125
#define IDC_RADIO_LOG_CONN              1126
#define IDC_CUSTOM2                     1126
#define IDC_COMBO_FIRST_STATE           1126
#define IDC_RADIO_LOG_CONN2             1127
#define IDC_STATIC_FIRST_STATE_SCENE    1127
#define IDC_CUSTOM3                     1127
#define IDC_STATIC_PLACE_HOLDER         1128
#define IDC_STATIC_SECOND_STATE_SCENE   1128
#define IDC_BUTTON_DEL                  1129
#define IDC_EDIT_VALUE                  1129
#define IDC_SPIN_VALUE                  1130
#define IDC_SPIN_ANGLE                  1131
#define IDC_COMBO_STATES_SCENES         1131
#define IDC_EDIT_GR_VALUE               1131
#define IDC_EDIT_VALUE2                 1132
#define IDC_BUTTON_ADD_INC              1132
#define IDC_SPIN_GR_VALUE               1132
#define IDC_SPIN_ANGLE_SP               1132
#define IDC_SPIN_VALUE2                 1133
#define IDC_BUTTON_ADD_DEC              1133
#define IDC_COMBO_FIRST_COUNTER         1133
#define IDC_SPIN_SCALE_X                1133
#define IDC_COMBO_SECOND_COUNTER        1134
#define IDC_SPIN_SCALE_X_SP             1134
#define IDC_RADIO_PASS                  1135
#define IDC_COMBO_COUNTER               1135
#define IDC_SPIN_SCALE_Y                1135
#define IDC_RADIO_PASS2                 1136
#define IDC_SPIN_MAX_VALUE              1136
#define IDC_SPIN_SCALE_Y_SP             1136
#define IDC_SPIN_HEIGHT                 1137
#define IDC_EDIT_MAX_VALUE              1137
#define IDC_SPIN_SAVE_ID                1138
#define IDC_CHECK_USE_AUTOSAVE          1139
#define IDC_EDIT_SAVE_ID                1139
#define IDC_SPIN_AUTOSAVE               1140
#define IDC_EDIT_AUTOHIDE_TIME          1140
#define IDC_TAB                         1141
#define IDC_SPIN_AUTOHIDE_TIME          1141
#define IDC_BTN_AUTO_BND                1142
#define IDC_EDIT_OFFSET_X               1142
#define IDC_CHECK_HIDE_OBJ              1143
#define IDC_EDIT_OFFSET_Y               1143
#define IDC_CHECK_RESTORE_PREF          1144
#define IDC_SPIN_OFFSET_X               1144
#define IDC_BTN_STACK_STATE             1145
#define IDC_SPIN_OFFSET_Y               1145
#define IDC_EDIT_OFFS_Y                 1145
#define IDC_CHECK_GO                    1146
#define IDC_SLIDER_CUR_CADR             1147
#define IDC_COMBO_OPTIONS               1147
#define IDC_CHECK_MOUSE_STATE           1149
#define IDC_SLIDER_CADR                 1150
#define IDC_CHECK_MOUSE_HOVER_STATE     1150
#define IDC_SPIN_MAX_DIST               1150
#define IDC_CHECK_STAY_IN_INVENTORY     1151
#define IDC_EDIT_MAX_DIST               1151
#define IDC_SLIDER_CUR_CADR2            1152
#define IDC_EDIT_RADIUS                 1152
#define IDC_STATIC_CUR_FRAME            1153
#define IDC_EDIT_TIME                   1153
#define IDC_STATIC_CUR_FRAME2           1154
#define IDC_SPIN_RADIUS                 1154
#define IDC_STATIC_CUR_STATE            1155
#define IDC_SPIN_TIME                   1155
#define IDC_BTN_SAVE_DEFS               1156
#define IDC_HOTKEY1                     1156
#define IDC_SPIN_COLLISION_PATH         1156
#define IDC_BTN_LOAD_DEFS               1157
#define IDC_EDIT_KEY                    1157
#define IDC_SPIN_ROTATION_SPEED         1157
#define IDC_RADIO_LIST_CONTENT          1158
#define IDC_EDIT_COLLISION_PATH         1158
#define IDC_RADIO_LIST_CONTENT2         1159
#define IDC_SPIN_OFFS_X                 1159
#define IDC_EDIT_ROTATION_SPEED         1159
#define IDC_SPIN_X1                     1160
#define IDC_RADIO_LIST_CONTENT3         1160
#define IDC_SPIN_OFFS_Y                 1160
#define IDC_CHECK_CYCLEY                1160
#define IDC_SPIN_Y1                     1161
#define IDC_RADIO_LIST_CONTENT4         1161
#define IDC_COMBO_MOVEMENT_MODE         1161
#define IDC_SPIN_Z1                     1162
#define IDC_CHECK_BIND_TO_NET_NODE      1163
#define IDC_EDIT_START_ANGLE            1163
#define IDC_SPIN_START_ANGLE            1164
#define IDC_RADIO_MOVEMENT_LEFT         1165
#define IDC_RADIO_STATE_TYPE            1166
#define IDC_RADIO_MOVEMENT_UP           1166
#define IDC_RADIO_STATE_TYPE2           1167
#define IDC_RADIO_MOVEMENT_RIGHT        1167
#define IDC_RADIO_MOVEMENT_DOWN         1168
#define IDC_RADIO1                      1169
#define IDC_RADIO_MOVEMENT_UP_LEFT      1169
#define IDC_RADIO2                      1170
#define IDC_CHECK_COLLAPSE_SCENES       1170
#define IDC_RADIO_MOVEMENT_UP_RIGHT     1170
#define IDC_RADIO3                      1171
#define IDC_BUTTON_DIMS                 1171
#define IDC_RADIO_MOVEMENT_DOWN_RIGHT   1171
#define IDC_RADIO4                      1172
#define IDC_RADIO_MOVEMENT_DOWN_LEFT    1172
#define IDC_ASK_TEXT                    1173
#define IDC_RADIO5                      1173
#define IDC_RADIO_MOVEMENT_HORIZONTAL   1173
#define IDC_BUTTON_ACCELERATION         1173
#define IDC_CHECK_CA_TO_FIRST           1174
#define IDC_RADIO_TO_IMAGE              1174
#define IDC_RADIO_MOVEMENT_VERTICAL     1174
#define IDC_SPIN_ACCELERATION           1174
#define IDC_SPIN_START_DELAY            1175
#define IDC_RADIO_MOVEMENT_EIGHT_DIRS   1175
#define IDC_SPIN_MAX_SPEED              1175
#define IDC_SPIN_STATE_DURATION         1176
#define IDC_CHECK_MOVE2INVENTORY        1177
#define IDC_RADIO_MOVEMENT_SMOOTH2      1177
#define IDC_PIC_SEL                     1178
#define IDC_SPIN_CAM_MODE_WORK_TIME     1178
#define IDC_RADIO_MOVEMENT_FOUR_DIRS    1178
#define IDC_PIC_SELECTOR                1179
#define IDC_SPIN_CAM_MODE_SCROLL_SPEED  1179
#define IDC_BTN_ADD_TYPE                1180
#define IDC_SPIN_CAM_MODE_SCROLL_DISTANCE 1180
#define IDC_BTN_ADD_CELLSET             1181
#define IDC_EDIT_SOUND_DELAY            1181
#define IDC_BTN_LOAD_FROM_FILE          1182
#define IDC_BTN_REMOVE_TYPE             1182
#define IDC_SPIN_SOUND_DELAY            1182
#define IDC_STATIC_TYPE                 1183
#define IDC_EDIT_TEXT_DELAY             1183
#define IDC_SPIN_TEXT_DELAY             1184
#define IDC_CUSTOM                      1185
#define IDC_CHECK_IMMOVABLE             1186
#define IDC_CUSTOM_SCENE_VIDEO          1186
#define IDC_STATIC_VER                  1187
#define IDC_CHECK_PLAY_WHILE_VIDEO      1187
#define IDC_BNT_CLR_TEXT                1188
#define IDC_CHECK_CYCLE                 1188
#define IDC_CHECK_DLG_PHRASE            1189
#define IDC_SLIDER_VOLUME               1189
#define IDC_EDIT_VOLUME                 1190
#define IDC_LIST_FILES                  1191
#define IDC_EDIT_GAME_NAME              1191
#define IDC_CHECK_NO_SWITCH_OFF         1192
#define IDC_BTN_SEL_FILES               1193
#define IDC_RADIO_LEFT_ALIGN            1193
#define IDC_CHECK_NO_RESTART            1193
#define IDC_RADIO_CONVERT_1             1194
#define IDC_RADIO_RIGHT_ALIGN           1194
#define IDC_RADIO_CONVERT_2             1195
#define IDC_RADIO_HORZ                  1195
#define IDC_RADIO_CONVERT3              1196
#define IDC_RADIO_TOP_ALIGN             1196
#define IDC_DISABLE_MOUSE               1197
#define IDC_RADIO_BOTTOM_ALIGN          1197
#define IDC_RADIO_VERT                  1198
#define IDC_BUTTON_SELECT_TDB           1199
#define IDC_EDIT_DB_FILE                1200
#define IDC_COMBO_SHORT_PHRASE_ID       1201
#define IDC_COMBO_FULL_PHRASE_ID        1202
#define IDC_EDIT_SHORT_PHRASE_TEXT      1203
#define IDC_EDIT_SHORT_PHRASE_TEXT2     1204
#define IDC_EDIT_LONG_PHRASE_TEXT2      1204
#define IDC_EDIT_SERIAL_KEY             1204
#define IDC_EDIT_SETTED_INVENTORY       1205
#define IDC_OBJECT_LIST                 1206
#define IDC_STATIC_TEXT                 1207
#define IDC_STATIC_1                    1208
#define IDC_EDIT_MOVE_RADIUS            1209
#define IDC_EDIT_MOVE_SPEED             1210
#define IDC_SPIN_MOVE_SPEED             1211
#define IDC_SPIN_MOVE_RADIUS            1212
#define IDC_CHECK_INTERRUPT_STATE_BY_CLICK 1213
#define IDC_BUTTON_COLOR                1214
#define IDC_CHECK_MOVE_TO_ZONE          1214
#define IDC_RADIO_OUTPUT_ARRANGEMENT    1215
#define IDC_BUTTON_COLOR2               1215
#define IDC_RADIO_OUTPUT_ARRANGEMENT2   1216
#define IDC_BUTTON_SAVE_FONT_COLOR      1216
#define IDC_STATIC_COLOR                1217
#define IDC_CHECK_MOVE_ON_OBJECT        1217
#define IDC_BUTTON_SHADOW_COLOR         1217
#define IDC_EDIT_HORZ_BORDER            1218
#define IDC_BUTTON_HILITE_COLOR         1218
#define IDC_CHECK_RELATIVE_CA           1218
#define IDC_STATIC_COLOR2               1219
#define IDC_STATIC_HILITE_COLOR         1219
#define IDC_CHECK_ACTIVATE_PERSONAGE    1219
#define IDC_BUTTON_HILITE_COLOR2        1219
#define IDC_COMBO_SLIDER_NAMES          1220
#define IDC_COMBO_SLIDER_TYPES          1221
#define IDC_TEXT_VIEW                   1223
#define IDC_BTN_SEL_SHORT_PHRASE_ID     1225
#define IDC_BTN_SEL_LONG_PHRASE_ID      1226
#define IDC_LONG_PHRASE_ID              1227
#define IDC_COMBO_FONTS                 1228
#define IDC_EDIT_FONT_FILE              1229
#define IDC_BTN_SELECT_FONT_FILE        1230
#define IDC_EDIT_TRANSPARENCY           1231
#define IDC_SPIN_TRANSPARENCY           1232
#define IDC_SPIN_FOLLOW_RADIUS_MIN      1233
#define IDC_EDIT_ADDIT_X                1233
#define IDC_EDIT_FOLLOW_RADIUS_MIN      1234
#define IDC_SPIN_ADDIT_X                1234
#define IDC_EDIT_FOLLOW_RADIUS_MAX      1235
#define IDC_COMBO_OBJECTS               1235
#define IDC_EDIT_ADDIT_Y                1235
#define IDC_SPIN_FOLLOW_RADIUS_MAX      1236
#define IDC_SPIN_ADDIT_Y                1236
#define IDC_EDIT_ATTACHER_OFFSET_X      1237
#define IDC_EDIT_ATTACHER_OFFSET_Y      1238
#define IDC_SPIN_ATTACHER_OFFSET_X      1239
#define IDC_SPIN_ATTACHER_OFFSET_Y      1240
#define IDC_BTN_SELECT_MUSIC_TRACK      1241
#define IDC_EDIT_MUSIC_TRACK            1242
#define IDC_SLIDER_MUSIC_TRACK_VOLUME   1243
#define IDC_COMBO_DEFAULT_FONT          1244
#define IDC_COMBO_MINIGAMES             1245
#define IDC_LIST_OBJECTS                1246
#define IDC_COMBO_INTERFACE_SCREENS     1246
#define IDC_EDIT_INI_FILE               1247
#define IDC_BTN_SELECT_FILE             1248
#define IDC_BUTTON_PARAMS               1249
#define IDC_SPIN_COUNT                  1250
#define IDC_EDIT_COUNT                  1251
#define IDC_BUTTON_PLAY_SOUND           1252
#define IDC_BUTTON_PLAY_SOUND2          1253
#define IDC_BUTTON_EDIT_ANIMATION       1253
#define IDC_COMBO_SCENE                 1253
#define IDC_STATIC_SCENES               1254
#define IDC_STATIC_SCENES1              1255
#define IDC_COMBO_SCENES1               1256
#define IDC_STATIC_SCENES2              1257
#define IDC_CHECK_ANIMATE_ROTATION      1258
#define IDC_CHECK_ANIMATED_ROTATION     1258
#define IDC_STATIC_OBJECTS1             1259
#define IDC_COMBO_OBJECTS1              1260
#define IDC_RADIO_ALIGN_HORIZONTAL      1260
#define IDC_STATIC_OBJECTS2             1261
#define IDC_RADIO_ALIGN_VERTICAL        1261
#define IDC_COMBO_OBJECTS2              1262
#define IDC_BUTTON_COND_LIST_EDITOR     1262
#define IDC_RADIO_ALIGN_HORIZONTAL2     1262
#define IDC_LIST_CONDITIONS             1263
#define IDC_RADIO_ALIGN_VERTICAL2       1263
#define IDC_COMBO_ALIGN                 1266
#define IDC_SLIDER_ALPHA                1267
#define IDC_RADIO_FADE_OFF              1268
#define IDC_COMBO_VALIGN                1268
#define IDC_RADIO_FADE_IN               1269
#define IDC_RADIO_FADE_OUT              1270
#define IDC_SLIDER1                     1271
#define IDC_SLIDER_COMPRESSION          1271
#define IDC_EDIT_OFFS_X                 1272
#define IDC_STATIC_OFFSET_X             1273
#define IDC_STATIC_OFFSET_Y             1274
#define IDC_MINIGAME_DLL_NAME           1275
#define IDC_SPIN_TEXT_LENGTH            1276
#define IDC_EDIT_TEXT_LENGTH            1277
#define IDC_EDIT_HALL_OF_FAME_SIZE      1278
#define IDC_SPIN_HALL_OF_FAME_SIZE      1279
#define IDC_COMBO_INFO_TYPE             1280
#define IDC_EDIT_PLAYER_ID              1281
#define IDC_SPIN_PLAYER_ID              1282
#define IDC_MUSIC_FILE_NAME             1282
#define IDS_REG_VAL_NAME_TE_NET_BIND_TO_NODE 4464
#define ID_OPEN_SCRT                    32771
#define ID_TBTN_RUN_TRIGGER_TEST        32772
#define ID_TBTN_INIT_DEBUG_CHECK        32773
#define IDC_CRT_TRIGGER                 32774
#define IDC_CRT_ANIMATION               32775
#define ID_TBTN_CLEAR_STARTS            32776
#define IDC_CRT_SCENE                   32777
#define IDC_CRT_STATIC_OBJ              32778
#define IDC_CRT_ANIMATED_OBJ            32779
#define IDC_CRT_MOVING_OBJ              32780
#define IDC_DRAW_ALL_BOUNDS             32781
#define IDC_PROPERIES                   32782
#define IDC_REMOVE                      32783
#define IDC_SAVE_SCRT                   32785
#define IDC_ANIMATION_LIST              32787
#define ID_TBTN_PROFILER_ON_OFF         32788
#define IDC_CRT_PROJ                    32789
#define ID_BUTTON_RUN_SCENE             32790
#define IDC_BUTTON_RUN_SCRIPT           32791
#define IDC_RUN_ANIM_EDITOR             32795
#define ID_BTN_REL_ADD                  32796
#define ID_BUTTON32797                  32797
#define ID_BTN_MOVE                     32798
#define IDC_LAST                        32799
#define IDC_LAST_NAIL                   32799
#define IDC_SHOW_ALL_NET_PROJS          32801
#define ID_BTN_REL_DEL                  32802
#define ID_BTN_LINK_TYPE1               32803
#define ID_PLACEHOLDER1                 32803
#define ID_BTN_LINK_TYPE2               32804
#define ID_PLACEHODER2                  32804
#define ID_PLACEHOLDER3                 32805
#define ID_BUTTON_JOIN_PROJECT          32809
#define ID_BTN_LINK_TYPE_CHANGE         32810
#define IDC_TBTN_DEACTIVATE_TRIGGERS    32811
#define ID_BTN_DEL_CHAIN_NODE           32812
#define IDC_TBTN_ACTIVE_TO_BEGIN_FOR_ALL_TRGRS 32812
#define IDC_BTN_DEL_CHAIN_NODE          32813
#define IDC_MENU_MOVINGS_STOPS          32814
#define ID_BTN_EDIT_DIALOGS             32815
#define IDC_CREATE_STATICS              32816
#define IDC_TE_LINK_TYPE10              32816
#define IDC_CREATE_BACK                 32817
#define IDC_NET_PROPERTIES              32818
#define ID_SAVETOFILE_PROFILER_DATA     32818
#define IDC_EDIT_GAITS                  32819
#define IDC_EDIT_ANIMATION              32820
#define ID_BUTTON32821                  32821
#define IDC_EDIT_TRIGGERS               32822
#define ID_VIEW_OBJECTLIST              32823
#define IDC_CANCEL_REMOVING_EDGES       32825
#define IDC_ADD_MOUSE_STATES            32826
#define IDC_ADD_INTERF_TEXT_WINDOW      32827
#define IDC_SEL_SCENE                   32829
#define ID_TBTN_SHOW_ELEMENT            32830
#define ID_WAVE_TO_LOCALIZATION         32832
#define IDC_CREATE_STATE                32833
#define IDC_GAME_SETTINGS               32834
#define ID__25                          32835
#define ID__50                          32836
#define ID__100                         32837
#define ID__200                         32838
#define ID__300                         32839
#define ID__SEL_MASTAB                  32840
#define ID__FIT_HORZ                    32841
#define ID__FIT_VERT                    32842
#define ID_BTN_EDIT_GAME_AREA           32843
#define ID_BTN_EDIT_NET                 32844
#define ID_BTN_EDIT_SCENE               32845
#define IDC_ADD_VIDEO                   32847
#define IDC_PLAY_STOP_VIDEO             32848
#define IDC_MG_PARAMETERS               32849
#define IDC_LOAD_DBG_FROM_FILE          32850
#define IDC_STOP_VIDEO                  32851
#define IDC_STATE_CONDITION             32852
#define ID_TE_MAKE_LINK                 32852
#define ID_BTN_HAND                     32853
#define IDC_TE_LINK_SELECTED_TRIGGERS   32853
#define IDC_CRT_GRID_ZONE               32854
#define ID_BTN_MASK                     32855
#define IDC_CREATE_MASK                 32856
#define IDC_SOUND_LIST                  32857
#define IDC_EDIT_SOUND                  32858
#define IDC_APP_SETTINGS                32859
#define IDC_EDIT_FADE_TIME              32859
#define ID_LOCALIZATION_TO_WAVE         32860
#define IDC_STAT_DEPENDENCIES           32861
#define IDC_PERS_DIR                    32862
#define IDC_COLLAPSE_ALL                32863
#define IDC_EXPAND_ALL                  32864
#define ID_TBTN_PROPS                   32866
#define ID_X_                           32866
#define ID_TBTN_SCALE_PLUS              32867
#define ID_TBTN_SCALE_MINUS             32868
#define IDC_ADD_FONT                    32869
#define ID_TBTN_ALL_STATES_2_EDITOR     32870
#define IDC_CREATE_FONT                 32870
#define IDC_TE_LINK_DELETE              32871
#define ID_Menu32871                    32871
#define IDC_TE_LINK_CHANGE_TYPE         32872
#define IDC_ADD_INTERF_CONTER           32872
#define IDC_TE_TGR_ELE_DELETE           32873
#define IDC_ADD_INTERF_COUNTER          32873
#define IDC_NOT_CONTROLED_PERS          32875
#define IDC_ADJUST_GAME_AREA            32876
#define IDC_STATE_DIMS                  32880
#define IDC_STATE_HAS_BOUND             32881
#define IDC_TE_SHOW_CONDITION           32882
#define IDC_TE_PROPETIES                32884
#define IDC_STACK_STATE                 32885
#define IDC_COORDS_ANIMATION            32886
#define IDC_CRT_NEW_INVENTORY           32887
#define IDC_ADD_CELL_SET                32889
#define IDC_REMOVE_CELL_SET             32890
#define ID_TBTN_ENTRY_FOR_DYN_OBJ       32892
#define ID_TBTN_ENTRY_FOR_MOUSE         32893
#define ID_TBTN_ENTRY_FOR_PERS          32894
#define ID_TBTN_ENTRY_FOR_DIALOGS       32895
#define IDS_OPEN_MINIGAME_DLL_FILTER    32896
#define IDS_OPEN_MINIGAME_DLL_TITLE     32897
#define IDS_OPEN_MUSIC_TRACK_FILTER     32898
#define IDS_COND_TMPL_MG_IN_STATE       32899
#define IDS_STATICS_ADDED_SUCCESSFULL   32900
#define IDC_TE_MAKE_ACTIVE              32901
#define IDS_SAVE_PROFILER_DATA_FILTER   32902
#define IDS_INVALID_SCALE_INPUT         33142
#define IDS_INTERF_SLDR_PURPOSE_MUSIC_VOLUME 33144
#define IDS_MOVEMENT_FOUR_DIRS          33216
#define IDS_TEXTDB_FILE_EXT             33240
#define IDS_OPEN_SCRIPT_EXT             61204
#define IDS_OPEN_SCRIPT_FILTER          61205
#define IDS_OPEN_SPRITE_EXT             61206
#define IDS_OPEN_SPRITE_FILTER          61207
#define IDS_STATIC_OBJS_NODE            61208
#define IDS_ANIMATED_OBJS_NODE          61209
#define IDS_MOVING_OBJS_NODE            61210
#define IDS_GLOBAL_NODE                 61211
#define IDS_LOCATIONS_NODE              61212
#define IDS_SCENES_NODE                 61213
#define IDS_ANIMATIONS_NODE             61214
#define IDS_TRIGGERS_NODE               61215
#define IDS_COORDS_ANIMATIONS_NODE      61216
#define IDS_ACTIONS_NODE                61217
#define IDS_EM_NO_SCENE_SELECTED        61218
#define IDS_NEW_SCRIPT_FILTER           61219
#define IDS_EM_CNNT_GET_REL_PATH        61220
#define IDS_ANIMATION_COLOUMN_NAME      61221
#define IDS_FRAME_COUNT_COLOUMN_NAME    61222
#define IDS_DEL_ANIMATION_MSG           61223
#define IDS_DEL_SOUND_MSG               61224
#define IDS_OPEN_ANIMATION_EXT          61225
#define IDS_OPEN_ANIMATION_FILTER       61226
#define IDS_NEW_ANIM_NAME               61227
#define IDS_NAME_REPEATED               61228
#define IDS_ANIMATION_EDITOR_FILE_NAME  61229
#define IDS_ERR_MSG_CAPTION             61230
#define IDS_CNT_LOAD_ANIMATION_EDITOR   61231
#define IDS_CLMN_ANIMATION_NAME         61232
#define IDS_CLMN_OBJ_STATE_NAME         61233
#define IDS_CLMN_SOUND_NAME             61234
#define IDS_WIZARD_CAP_ANIMATION_ADD    61235
#define IDS_DEL_STATE_MSG               61236
#define IDS_NO_SELECTION_MSG            61237
#define IDS_CLMN_OBJ_STATE_NUMBER       61238
#define IDS_CLMN_DIR_NUMBER             61239
#define IDS_CLMN_GAITS                  61240
#define IDS_CLMN_STOPS                  61241
#define IDS_NET_NODE_NAME               61242
#define IDS_DIFF_H                      61243
#define IDS_DEF_FONT_FILE_NAME          61244
#define IDS_DEF_FONT_IDX_FILE_NAME      61245
#define IDS_TITLE_FOR_SEL_FOLDER_DLG    61246
#define IDS_DEF_CURSOR_FILE_NAME        61247
#define IDS_NEW_PROJ_FILE_NAME          61248
#define IDS_NEW_LOCATION_NAME           61249
#define IDS_CNNT_CRT_LOACATION          61250
#define IDS_NEW_SCENE_NAME              61251
#define IDS_NEW_ANIMATED_OBJ_NAME       61252
#define IDS_CNNT_CRT_ANIMATED_OBJ       61253
#define IDS_NEW_MOVING_OBJ_NAME         61254
#define IDS_CNNT_CRT_MOVING_OBJ         61255
#define IDS_NEW_STATIC_OBJ_NAME         61256
#define IDS_CNNT_CRT_STATIC_OBJ         61257
#define IDS_GAME_EXE_FILE_NAME          61258
#define IDS_CNT_LOAD_GAME_EXE           61259
#define IDS_CHANGE_STATE_DLG_CAPTION    61260
#define IDS_CHANGE_ANIM_DLG_CAPTION     61261
#define IDS_PPCAP_SCENE_PROPERTIES      61262
#define IDS_PPCAP_STATIC_OBJ_PROPERTIES 61263
#define IDS_PPCAP_ANIMATED_OBJ_PROPERTIES 61264
#define IDS_PPCAP_MOVING_OBJ_PROPERTIES 61265
#define IDS_DEL_CAP                     61266
#define IDS_DEL_OBJECT                  61267
#define IDS_CLMN_CURSOR_NAME            61268
#define IDS_FILE_EXT_REG_KEY            61269
#define IDS_PROG_ID_REG_KEY             61270
#define IDS_PROG_ID_KEY_VALUE           61271
#define IDS_APPS_SUB_KEY                61272
#define IDS_FRIENDLY_APP_NAME           61273
#define IDS_EM_CDNT_CRT_ANIMATION       61274
#define IDS_NEW_ANIMATION_FILE_NAME     61275
#define IDS_SAVE_PROJ_MSG               61276
#define IDS_TGR_EDTR_WND_CAP            61277
#define IDS_CB_FORMAT_NAME              61278
#define IDS_NEW_CHAIN_NAME              61279
#define IDS_FILE_EXT_REG_KEY2           61280
#define IDS_CHAIN_NODE_NO_NAME          61281
#define IDS_SECTION_CHAINS_NAME         61282
#define IDS_VALUE_COUNT                 61283
#define IDS_SECTION_CHAIN               61284
#define IDS_VALUE_NODES                 61285
#define IDS_VALUE_NAME                  61286
#define IDS_VALUE_TYPES                 61287
#define IDS_VALUE_NUM_LEVELS            61288
#define IDS_DEL_CHAINS_MSG              61289
#define IDS_MOUSE_OBJ_NODE              61290
#define IDS_OBJECT_STATES_NODE          61291
#define IDS_TE_NODE_HAS_RELATIONS       61292
#define IDS_VALUE_ROOT                  61293
#define IDS_TE_ROOT_NODE_NAME           61294
#define IDS_PPCAP_MOUSE_OBJ_PROPERTIES  61295
#define IDS_CLMN_MOVING_NAME            61296
#define IDS_NEW_MOVING_NAME             61297
#define IDS_CLMN_DIR_NAME               61298
#define IDS_CLMN_SPEED_NAME             61299
#define IDC_STATIC_ANIM_CAPTION1        61300
#define IDC_STATIC_ANIM_CAPTION2        61301
#define IDS_SEL_GAINT_OR_ANIM           61302
#define IDS_NOTHING                     61303
#define IDS_PROPPAGE_CAPTION_GAITS      61304
#define IDS_PROPPAGE_CAPTION_STOPS      61305
#define IDS_STOPS_CATALOG               61306
#define IDS_GAITS_CATALOG               61307
#define IDS_NEW_BACKGROUND_OBJ_NAME     61308
#define IDS_OSD_CAP_SEL_BACK            61309
#define IDS_OSD_CAP_SEL_STAT_OBJ        61310
#define IDS_OSD_CAP_SAVE                61311
#define IDS_OSD_CAP_CREATE              61312
#define IDS_OSD_CAP_OPEN                61313
#define IDS_OSD_CAP_SAVE_AS             61314
#define IDS_OSD_CAP_SEL_ANIM            61315
#define IDS_OSD_CAP_SEL_STAT_OBJS       61316
#define IDS_CNNT_CLOSE_EDT_COORD_ANIM   61317
#define IDS_GAITS_LEFT                  61318
#define IDS_GAITS_RIGHT                 61319
#define IDS_GAITS_BACK                  61320
#define IDS_GAITS_FORWARD               61321
#define IDS_GAITS_INTERIM               61322
#define IDS_CLMN_SCENE_NAME             61323
#define IDS_ITEM_CRT_NEW_SCENE          61324
#define IDS_STR_RESOLUTIONS             61325
#define IDS_CAP_GAME_SETTINGS           61326
#define IDS_CAP_BROWSE_BUTTON1          61327
#define IDS_CAP_BROWSE_BUTTON2          61328
#define IDS_CAP_BROWSE_BUTTON3          61329
#define IDS_CLMN_DIR_NAMES              61330
#define IDS_CAP_ANIMS_LIST_DLG          61331
#define IDS_NO_SCENE_FOUND              61332
#define IDS_CNNT_CRT_SCENE              61333
#define IDS_CAP_ANIMS_UNIQ_LIST_DLG     61334
#define IDS_ANIM_LIST_EMPTY             61335
#define IDS_CRT_OBJ_SUCC                61336
#define IDS_ERR_EMPTY_NAME              61337
#define IDS_ADD_STATES_SUCC             61338
#define IDS_ADD_STATES_ERR              61339
#define IDS_PROPPAGE_CAPTION_ADD_DYN_OBJ 61340
#define IDS_PROPPAGE_CAPTION_ADD_MOV_OBJ 61341
#define IDS_PROPPAGE_CAPTION_ADD_STATES_DYN_OBJ 61342
#define IDS_PROPPAGE_CAPTION_ADD_STATES_MOV_OBJ 61343
#define IDS_ACCESSIBLE_GAITS            61344
#define IDS_GAIT_USED                   61345
#define IDS_STATE_USED                  61346
#define IDS_LAST_STATE_IN_OBJ           61347
#define IDS_AUTOSAVE_BEGIN              61348
#define IDS_AUTOSAVE_END                61349
#define IDS_GAIT_USED2                  61350
#define IDS_ANIMATION_USED_IN_SCENE     61351
#define IDS_ANIMATION_USED2             61352
#define IDS_ANIMATION_USED_IN_SCENE2    61353
#define IDS_ANIMATION_USED_IN_SCENE_AND_GAIT 61354
#define IDS_ANIMATION_USED_IN_SCENE_AND_GAIT2 61355
#define IDS_ANIMATION_USED_IN_GAIT      61356
#define IDS_VIDEO_CATALOG               61357
#define IDS_OPEN_VIDEO_FILTER           61358
#define IDS_OSD_CAP_SEL_VIDEO           61359
#define IDS_DEL_VIDEO                   61360
#define IDS_COND_TMPL_MOUSE_CLICK       61361
#define IDS_COND_TMPL_MOUSE_OBJECT_CLICK 61362
#define IDS_COND_TMPL_OBJECT_IN_ZONE    61363
#define IDS_COND_TMPL_TIMER             61364
#define IDS_COND_MOUSE_CLICK_OBJ_SELF   61365
#define IDS_DEL_CONDITION_MSG           61366
#define IDS_COND_TMPL_STATIC_DIRECTION  61367
#define IDS_COND_TMPL_WALK_DIRECTION    61368
#define IDS_GAIT_LIST_EMPTY             61369
#define IDS_NEW_GRID_ZONE_NAME          61370
#define IDS_ITEM_CRT_NEW_ANIM_OBJECT    61371
#define IDS_EDIT_WORK_SAVED_SUCC        61372
#define IDS_MASK_NAME                   61373
#define IDS_ERR_NAME_EMPTY              61374
#define IDS_GRID_ZONE_PROPERTIES        61375
#define IDS_EDT_CNTR_DLG_CAP1           61376
#define IDS_EDT_CNTR_DLG_CAP2           61377
#define IDS_EDT_CNTR_DLG_CAP3           61378
#define IDS_EDT_CNTR_DLG_CAP4           61379
#define IDS_PRGSS_DLG_CAP_ADD_ANIM      61380
#define IDS_CAP_SOUNDS_LIST_DLG         61381
#define IDS_CAP_SOUNDS_UNIQ_LIST_DLG    61382
#define IDS_SOUND_COLOUMN_NAME          61383
#define IDS_OPEN_SOUND_EXT              61384
#define IDS_OPEN_SOUND_FILTER           61385
#define IDS_OSD_CAP_SEL_SOUND           61386
#define IDS_SOUND_USED_IN_SCENE         61387
#define IDS_SOUND_USED                  61388
#define IDS_REG_SEC_NAME_GEN_OPT        61389
#define IDS_REG_VAL_NAME_LAST_CUR_DIR   61390
#define IDS_REG_SEC_NAME_RECENT_FILES   61391
#define IDS_REG_VAL_NAME_RECENT_FILE    61392
#define IDS_FILE_NOT_FOUND              61393
#define IDS_SETTING_NAME_AUTOSAVE       61394
#define IDS_SETTING_NAME_AUTOSAVE_PERIOD 61395
#define IDS_REG_VAL_NAME_AUTOSAVE       61396
#define IDS_REG_VAL_NAME_AUTOSAVE_PERIOD 61397
#define IDS_SCN_ONE_CADR_OBJECTS        61398
#define IDS_PPCAP_NET_PROPERTIES        61399
#define IDS_RESOURCE_CATALOG            61400
#define IDS_DISK_DYNOBJ_CATALOG         61401
#define IDS_STATIC_OBJ_CATALOG          61402
#define IDS_ANIMATION_SAVE_CATALOG      61403
#define IDS_CUR_FRAME_TMPL              61404
#define IDS_CAP_STATE_STACKER           61405
#define IDS_ERR_NO_ANIMATION_IN_STATE   61406
#define IDS_ERR_NO_GAIT_IN_STATE        61407
#define IDS_REG_SEC_NAME_NET_DEFAULTS   61408
#define IDS_REG_VAL_NAME_NET_ANGLE_X    61409
#define IDS_REG_VAL_NAME_NET_ANGLE_Y    61410
#define IDS_REG_VAL_NAME_NET_ANGLE_Z    61411
#define IDS_SETTING_NAME_NET_ANGLE_X    61412
#define IDS_SETTING_NAME_NET_ANGLE_Y    61413
#define IDS_SETTING_NAME_NET_ANGLE_Z    61414
#define IDS_REG_VAL_NAME_NET_VERT_OFFSET 61415
#define IDS_SETTING_NAME_NET_VERT_OFFSET 61416
#define IDS_REG_VAL_NAME_NET_FOCUS      61417
#define IDS_SETTING_NAME_NET_FOCUS      61418
#define IDS_REG_VAL_NAME_NET_SX         61419
#define IDS_SETTING_NAME_NET_SX         61420
#define IDS_REG_VAL_NAME_NET_SY         61421
#define IDS_SETTING_NAME_NET_SY         61422
#define IDS_REG_VAL_NAME_NET_CELL_SZ    61423
#define IDS_SETTING_NAME_NET_CELL_SZ    61424
#define IDS_CANT_FIND_DYNAMIC_OBJ_FOLDER 61425
#define IDS_GLOBAL_ANIMATION_CATALOG    61426
#define IDS_INI_SEC_NAME_TREE           61427
#define IDS_INI_KEY_NAME_SELECTED       61428
#define IDS_INI_KEY_NAME_CUR_SCENE      61429
#define IDS_INI_KEY_NAME_NET_DRAW_MODE  61430
#define IDS_ZONE_VERTEX_COINCIDE        61431
#define IDS_DLG_CURSOR_NAME             61432
#define IDS_AUTOMATIC_SELECTED_ANIM     61433
#define IDS_SETTING_NAME_TE_NET_CELL_SX 61434
#define IDS_SETTING_NAME_TE_NET_CELL_SY 61435
#define IDS_SETTING_NAME_TE_NET_BIND_TO_NODE 61436
#define IDS_REG_SEC_NAME_TE             61437
#define IDS_REG_VAL_NAME_TE_NET_CELL_SX 61438
#define IDS_REG_VAL_NAME_TE_NET_CELL_SY 61439
#define IDS_SELECT_TEXT_FILE            61500
#define IDS_ALL_FILES_FILTER            61501
#define IDS_COND_TMPL_MOUSE_DLG_CLICK   61502
#define IDS_ACCESSIBLE_DLG_FILES        61503
#define IDS_CNNT_CLOSE_EDIT_STATE_DIMS  61504
#define IDS_ANIMATION_USED_IN_SCENE_GAIT_AND_GLOBAL_OBJ 61505
#define IDS_ANIMATION_USED_IN_GAIT_AND_GLOBAL_OBJ 61506
#define IDS_ANIMATION_USED_IN_SCENE2_AND_GLOBAL_OBJ 61507
#define IDS_SOUND_USED_IN_GLOBAL_OBJS   61508
#define IDS_SOUND_USED_IN_SCENE_AND_GLOBAL_OBJS 61509
#define IDS_ANIMATION_USED_IN_GLOBAL_OBJ 61510
#define IDS_COND_TMPL_WALK_DIRECTION2   61511
#define IDS_COND_TMPL_STATIC_DIRECTION2 61512
#define IDS_SETTING_NAME_SCENE_TB_LEFT  62002
#define IDS_SETTING_NAME_SCENE_TB_TOP   62003
#define IDS_SETTING_NAME_SCENE_TB_RIGHT 62004
#define IDS_SETTING_NAME_SCENE_TB_BOTTOM 62005
#define IDS_REG_VAL_NAME_SCENE_TB_LEFT  62006
#define IDS_REG_VAL_NAME_SCENE_TB_TOP   62007
#define IDS_REG_VAL_NAME_SCENE_TB_RIGHT 62008
#define IDS_REG_VAL_NAME_SCENE_TB_BOTTOM 62048
#define IDS_SETTING_NAME_SCENE_TB_VISIBLE 62049
#define IDS_REG_VAL_NAME_SCENE_TB_VISIBLE 62050
#define IDS_SETTING_NAME_TE_TB_LEFT     62051
#define IDS_SETTING_NAME_TE_TB_TOP      62052
#define IDS_SETTING_NAME_TE_TB_RIGHT    62053
#define IDS_SETTING_NAME_TE_TB_BOTTOM   62054
#define IDS_REG_VAL_NAME_TE_TB_LEFT     62055
#define IDS_REG_VAL_NAME_TE_TB_TOP      62056
#define IDS_REG_VAL_NAME_TE_TB_RIGHT    62057
#define IDS_REG_VAL_NAME_TE_TB_BOTTOM   62058
#define IDS_SETTING_NAME_TE_TB_VISIBLE  62059
#define IDS_OSD_CAP_SEL_STAT_OBJS2      62060
#define IDS_REG_VAL_NAME_TE_TB_VISIBLE  62061
#define IDS_OSD_CAP_SEL_CELL_TYPE       62062
#define IDS_REG_SEC_NAME_TOOLBARS       62063
#define IDS_CNNT_CRT_TRIGGER_CHAIN      62064
#define IDS_NEW_TRIGGER_CHAIN_NAME      62065
#define IDS_GLOBAL_MOVING_OBJS_NODE     62066
#define IDS_GLOBAL_STATES_NODE          62067
#define IDS_INI_SEC_NAME_APP            62068
#define IDS_INI_KEY_NAME_ACTIVE_VIEW    62069
#define IDS_ACCESSIBLE_ANIMATION        62070
#define IDS_ACCESSIBLE_SOUNDS           62071
#define IDS_SETTING_NAME_TE_NET_AMONG_CELL_SX 62072
#define IDS_REG_VAL_NAME_TE_NET_AMONG_CELL_SX 62073
#define IDS_SETTING_NAME_TE_NET_AMONG_CELL_SY 62074
#define IDS_REG_VAL_NAME_TE_NET_AMONG_CELL_SY 62075
#define IDS_SETTING_NAME_PT_COLLAPSE_SCENES 62076
#define IDS_REG_VAL_NAME_PT_COLLAPSE_SCENES 62077
#define IDS_ASK_ADD_CONDITION           62078
#define IDS_CNNT_CLOSE_STACK_STATE      62079
#define IDS_INVENTORY_OBJS_NODE         62080
#define IDS_INVENTORY_DEFAULT_NAME      62081
#define IDS_ACTIVE_INVENTORY            62082
#define IDS_NO_INVENTORY                62083
#define IDS_NO_CELL_TYPE_SELECTED       62084
#define IDS_CELLSET_CELL_TYPE_USED_IN_OBJ 62085
#define IDS_SETTING_NAME_COND_MOUSE_CLICK_COLOR 62086
#define IDS_REG_VAL_NAME_COND_MOUSE_CLICK_COLOR 62087
#define IDS_SETTING_NAME_COND_MOUSE_OBJECT_CLICK_COLOR 62088
#define IDS_REG_VAL_NAME_COND_MOUSE_OBJECT_CLICK_COLOR 62089
#define IDS_SETTING_NAME_COND_OBJECT_IN_ZONE_COLOR 62090
#define IDS_REG_VAL_NAME_COND_OBJECT_IN_ZONE_COLOR 62091
#define IDS_SETTING_NAME_COND_PERSONAGE_WALK_DIRECTION_COLOR 62092
#define IDS_REG_VAL_NAME_COND_PERSONAGE_WALK_DIRECTION_COLOR 62093
#define IDS_SETTING_NAME_COND_PERSONAGE_STATIC_DIRECTION_COLOR 62094
#define IDS_REG_VAL_NAME_COND_PERSONAGE_STATIC_DIRECTION_COLOR 62095
#define IDS_SETTING_NAME_COND_TIMER_COLOR 62096
#define IDS_REG_VAL_NAME_COND_TIMER_COLOR 62097
#define IDS_SETTING_NAME_COND_MOUSE_DIALOG_CLICK_COLOR 62098
#define IDS_REG_VAL_NAME_COND_MOUSE_DIALOG_CLICK_COLOR 62099
#define IDS_CLMN_SELECTED_FILES         62100
#define IDS_CLMN_SELECTED_FOLDERS       62101
#define IDS_CLMN_SELECTED_FOLDER        62102
#define IDS_WIZARD_CAP_GAME_GLOBAL_SETTINGS 62103
#define IDS_OPEN_MINIGAME_CONFIG_FILTER 62104
#define IDS_OPEN_MINIGAME_CONFIG_EXT    62105
#define IDS_OPEN_MINIGAME_CONFIG_TITLE  62106
#define IDS_NEW_MINIGAME_NAME           62107
#define IDS_MG_STATE_NAME_LOSS          62108
#define IDS_MG_STATE_NAME_WIN           62109
#define IDS_REG_VAL_NAME_COND_MINIGAME_IN_STATE_COLOR 62110
#define IDS_SETTING_NAME_COND_MINIGAME_IN_STATE_COLOR 62111
#define IDS_OPEN_QDA_TGA_FILTER         62112
#define IDS_REG_VAL_NAME_COND_OBJECT_STATE_COLOR 62113
#define IDS_SETTING_NAME_COND_OBJECT_STATE_COLOR 62114
#define IDS_REG_VAL_NAME_COND_PERSONAGE_STATIC_DIRECTION_COLOR2 62115
#define IDS_REG_VAL_NAME_COND_MOUSE_ZONE_CLICK_COLOR 62115
#define IDS_SETTING_NAME_COND_MOUSE_ZONE_CLICK_COLOR 62116
#define IDS_REG_VAL_NAME_COND_MOUSE_OBJECT_ZONE_CLICK_COLOR 62117
#define IDS_SETTING_NAME_COND_MOUSE_OBJECT_ZONE_CLICK_COLOR 62118
#define IDS_REG_VAL_NAME_COND_OBJECT_STATE_WAS_ACTIVATED_COLOR 62119
#define IDS_SETTING_NAME_COND_OBJECT_STATE_WAS_ACTIVATED_COLOR 62120
#define IDS_REG_VAL_NAME_COND_OBJECT_STATE_WAS_NOT_ACTIVATED_COLOR 62121
#define IDS_SETTING_NAME_COND_OBJECT_STATE_WAS_ACTIVATED_COLOR2 62122
#define IDS_SETTING_NAME_COND_OBJECT_STATE_WAS_NOT_ACTIVATED_COLOR 62122
#define IDS_SETTING_NAME_SV_LEFT_RIGHT_OFFSET 62123
#define IDS_REG_VAL_NAME_SV_LEFT_RIGHT_OFFSET 62124
#define IDS_SETTING_NAME_SV_LEFT_RIGHT_OFFSET2 62125
#define IDS_SETTING_NAME_SV_TOP_BOTTOM_OFFSET 62125
#define IDS_REG_VAL_NAME_SV_TOP_BOTTOM_OFFSET 62126
#define IDS_OPEN_FONT_FILE_FILTER       62127
#define IDS_OPEN_FONT_FILE_EXT          62128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32874
#define _APS_NEXT_CONTROL_VALUE         1283
#define _APS_NEXT_SYMED_VALUE           344
#endif
#endif
