						 /********************************************************************
	created:	2002/08/01
	created:	1:8:2002   15:13
	filename: 	D:\Projects\Quest\QuestEditor\SettingDefs.h
	file path:	D:\Projects\Quest\QuestEditor
	file base:	SettingDefs
	file ext:	h
	author:		Илюха
	
	purpose:	содерижит значения по умолчанию для настроек
*********************************************************************/

#ifndef __SETTING_DEFAULTS__
#define __SETTING_DEFAULTS__

#define DECLARE_INT_DEFALUT(_NAME, _val) \
const int _NAME##_DEF_VALUE = _val

#define DECLARE_STR_DEFALUT(_NAME, _val) \
LPCTSTR const _NAME##_DEF_VALUE = _val

#define DEFAULT_VALUE(_NAME) (_NAME##_DEF_VALUE)

/*
 *	Свойства автосохранения
 */
DECLARE_INT_DEFALUT(AUTOSAVE, TRUE);
DECLARE_INT_DEFALUT(AUTOSAVE_PERIOD, 120000);

/*
 *	Свойства сетки
 */
DECLARE_INT_DEFALUT(NET_ANGLE_X, 45);
DECLARE_INT_DEFALUT(NET_ANGLE_Y, 0);
DECLARE_INT_DEFALUT(NET_ANGLE_Z, 0);
DECLARE_INT_DEFALUT(NET_VERT_OFFSET, 0);
DECLARE_INT_DEFALUT(NET_FOCUS, 6000);
DECLARE_INT_DEFALUT(NET_SX, 46);
DECLARE_INT_DEFALUT(NET_SY, 46);
DECLARE_INT_DEFALUT(NET_CELL_SZ, 32);

DECLARE_STR_DEFALUT(NET_SCALE_POW, _T("1"));
DECLARE_STR_DEFALUT(NET_SCALE_Z_OFFSET, _T("0"));
/*
 *	Настройки сетки для редактора триггеров
 */
DECLARE_INT_DEFALUT(TE_NET_CELL_SX, 256);
DECLARE_INT_DEFALUT(TE_NET_CELL_SY, 32);
DECLARE_INT_DEFALUT(TE_NET_AMONG_CELL_SX, 32);
DECLARE_INT_DEFALUT(TE_NET_AMONG_CELL_SY, 32);
DECLARE_INT_DEFALUT(TE_NET_BIND_TO_NODE, 1);
DECLARE_INT_DEFALUT(TE_SHOW_MENU_ON_LINK_CREATE, 0);

/*
 *	Настройки дерева проекта
 */
DECLARE_INT_DEFALUT(PT_COLLAPSE_SCENES, FALSE);

/*
 *	Цвета для условий, используемые по умолчанию
 */
/*
*/
const COLORREF DEFAULT_CONDTION_COLOR = RGB(220, 220, 220);
/*255, 128, 192*/
DECLARE_INT_DEFALUT(COND_MOUSE_CLICK_COLOR,							RGB(0, 255, 0));
DECLARE_INT_DEFALUT(COND_MOUSE_OBJECT_CLICK_COLOR,					RGB(0, 0, 255));
DECLARE_INT_DEFALUT(COND_OBJECT_IN_ZONE_COLOR,						RGB(255, 255, 0));
DECLARE_INT_DEFALUT(COND_PERSONAGE_WALK_DIRECTION_COLOR,			RGB(0, 255, 255));
DECLARE_INT_DEFALUT(COND_PERSONAGE_STATIC_DIRECTION_COLOR,			RGB(0, 200, 200));
DECLARE_INT_DEFALUT(COND_TIMER_COLOR,								RGB(255, 128,0));
DECLARE_INT_DEFALUT(COND_MOUSE_DIALOG_CLICK_COLOR,					RGB(0, 128, 0));
DECLARE_INT_DEFALUT(COND_MINIGAME_IN_STATE_COLOR,					RGB(222, 0, 255));
DECLARE_INT_DEFALUT(COND_OBJECT_STATE_COLOR,						RGB(192, 192, 192));
DECLARE_INT_DEFALUT(COND_MOUSE_ZONE_CLICK_COLOR,					RGB(141, 141, 100));
DECLARE_INT_DEFALUT(COND_MOUSE_OBJECT_ZONE_CLICK_COLOR,				RGB(128, 128, 0));
DECLARE_INT_DEFALUT(COND_OBJECT_STATE_WAS_ACTIVATED_COLOR,			RGB(192, 192, 192));
DECLARE_INT_DEFALUT(COND_OBJECT_STATE_WAS_NOT_ACTIVATED_COLOR,		RGB(170, 185, 200));
DECLARE_INT_DEFALUT(COND_OBJECTS_DISTANCE_COLOR,					RGB(255, 0, 0));
DECLARE_INT_DEFALUT(COND_PERSONAGE_ACTIVE_COLOR,					RGB(0, 128, 255));
DECLARE_INT_DEFALUT(COND_OBJECT_STATE_WAITING_COLOR,				RGB(192, 192, 192));

DECLARE_INT_DEFALUT(COND_OBJECT_STATE_ANIMATION_PHASE_COLOR,		DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_OBJECT_PREV_STATE_COLOR,					DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_STATE_TIME_GREATER_THAN_VALUE_COLOR,		DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_STATE_TIME_GREATER_THAN_STATE_TIME_COLOR,	DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_STATE_TIME_IN_INTERVAL_COLOR,				DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_COUNTER_GREATER_THAN_VALUE_COLOR,			DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_COUNTER_LESS_THAN_VALUE_COLOR,				DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_COUNTER_GREATER_THAN_COUNTER_COLOR,		DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_COUNTER_IN_INTERVAL_COLOR,					DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_OBJECT_ON_PERSONAGE_WAY_COLOR,				DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_KEYPRESS_COLOR,							DEFAULT_CONDTION_COLOR);
DECLARE_INT_DEFALUT(COND_ANY_PERSONAGE_IN_ZONE_COLOR,				DEFAULT_CONDTION_COLOR);

DECLARE_INT_DEFALUT(INVERSE_CONDITION_COLOR,						RGB(255, 128, 192));
DECLARE_INT_DEFALUT(STATE_FLAG_HIDE_OBJECT_COLOR,					RGB(120, 120, 120));

//Свойства окна просмотра сцены

DECLARE_INT_DEFALUT(SV_LEFT_RIGHT_OFFSET, 200);
DECLARE_INT_DEFALUT(SV_TOP_BOTTOM_OFFSET, 200);

#endif//__SETTING_DEFAULTS__
